/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! Publisher configuration, loaded from TOML. Every field has a default.
//!
//! TOML sections map 1:1 to the structs: `[mqtt]` (input side), `[mapping]`
//! (what to turn the reading into), `[uprotocol]` (output side). See
//! config/publisher.toml for a file with all defaults. `deny_unknown_fields`
//! turns a typo in the file into an error instead of an ignored setting.

use serde::Deserialize;
use std::path::Path;

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct PublisherConfig {
    pub mqtt: MqttConfig,
    pub mapping: MappingConfig,
    pub uprotocol: UProtocolConfig,
}

/// Where to get the readings from.
#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct MqttConfig {
    /// MQTT broker (Mosquitto) address.
    pub host: String,
    pub port: u16,
    /// Topic the AZ3166 publishes its readings on.
    pub topic: String,
    /// Our name at the broker; must be unique per connected client.
    pub client_id: String,
    /// Ping interval that keeps the connection alive when no data flows.
    pub keep_alive_s: u64,
}

impl Default for MqttConfig {
    fn default() -> Self {
        Self {
            host: "localhost".into(),
            port: 1883, // standard unencrypted MQTT port
            topic: "az3166/telemetry".into(),
            client_id: "vss-uprotocol-publisher".into(),
            keep_alive_s: 10,
        }
    }
}

/// How an MQTT reading is turned into VSS.
#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct MappingConfig {
    /// VSS path the temperature is mapped to. Default is the COVESA VSS
    /// hottest-cell signal (spec/Powertrain/TractionBattery.vspec, v4.0 to v6.1).
    pub vss_path: String,
    /// JSON key of the temperature (degrees Celsius) in the board's message.
    pub temperature_field: String,
    /// JSON key of the board's rolling counter (0..255, then wraps to 0).
    pub counter_field: String,
}

impl Default for MappingConfig {
    fn default() -> Self {
        Self {
            vss_path: "Vehicle.Powertrain.TractionBattery.Temperature.Max".into(),
            // Key names as sent by the AZ3166 firmware.
            temperature_field: "temperature_degC".into(),
            counter_field: "counter".into(),
        }
    }
}

/// Where to publish: together these form the topic //authority/entity/version/resource.
#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct UProtocolConfig {
    /// uProtocol device name, first part of the topic (//vehicle/...).
    pub authority: String,
    /// uEntity ID of this publisher; the Guardian subscribes to it.
    pub entity_id: u32,
    pub entity_version: u8,
    /// Resource (topic) ID of the temperature signal.
    pub resource_id: u16,
    /// Optional Zenoh configuration file (JSON5).
    pub zenoh_config: Option<String>,
}

impl Default for UProtocolConfig {
    fn default() -> Self {
        Self {
            authority: "vehicle".into(),
            // Must match the Guardian's input_topic //*/8001/1/8001.
            entity_id: 0x8001,
            entity_version: 1,
            resource_id: 0x8001,
            zenoh_config: None,
        }
    }
}

impl PublisherConfig {
    /// Reads and parses a TOML file.
    pub fn load(path: &Path) -> Result<Self, String> {
        let text = std::fs::read_to_string(path)
            .map_err(|e| format!("cannot read {}: {e}", path.display()))?;
        toml::from_str(&text).map_err(|e| e.to_string())
    }
}
