/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! VSS uProtocol Publisher: AZ3166 MQTT readings -> VSS -> uProtocol.
//!
//! # Where the publisher sits
//!
//! ```text
//! AZ3166 --MQTT--> Mosquitto --MQTT--> [this publisher] --uProtocol/Zenoh--> Guardian
//! ```
//!
//! It is a translator between two worlds: MQTT (what the board speaks) and
//! uProtocol (what the Guardian listens to). It does not judge the data.
//!
//! # Life of one reading
//!
//! 1. `main.rs` connects to the MQTT broker (rumqttc) and to Zenoh
//!    ([`publisher::zenoh_transport`]), then subscribes to `az3166/telemetry`.
//! 2. The board publishes all its sensor values once per second, e.g.
//!    `{"pressure_hPa": 1215.87, "temperature_degC": 24.65, ..., "counter": 31}`;
//!    the broker forwards it; the MQTT event loop in `main.rs` receives it.
//! 3. [`mapping::Mapper::map`] parses the JSON, takes `temperature_degC` and
//!    `counter` (ignores the rest) and returns a
//!    [`mapping::VssSample`] for
//!    `Vehicle.Powertrain.TractionBattery.Temperature.Max`.
//! 4. [`publisher::VssPublisher::publish`] serializes that sample to JSON,
//!    wraps it into a uProtocol PUBLISH uMessage with source
//!    `//vehicle/8001/1/8001` and sends it over Zenoh. The message id
//!    (UUIDv7) records the creation time; it is the sample time for the Guardian.
//! 5. The Guardian, subscribed to `//*/8001/1/8001`, receives it.
//!
//! # Modules
//!
//! - [`config`]: MQTT, mapping and uProtocol settings, loaded from TOML
//! - [`mapping`]: MQTT payload to VSS sample (pure, no I/O)
//! - [`publisher`]: VSS sample to uMessage on the uProtocol transport

pub mod config;
pub mod mapping;
pub mod publisher;
