/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! Entry point of the publisher (flow steps 1 and 2 in `lib.rs`).
//!
//! Sets up both ends (MQTT client, uProtocol transport), then runs the MQTT
//! event loop: every MQTT message from the board goes through the mapper and
//! the publisher.

use std::path::PathBuf;
use std::time::Duration;

use clap::Parser;
use rumqttc::{AsyncClient, Event, MqttOptions, Packet, QoS};
use tracing::{debug, info, warn};
use vss_publisher::config::PublisherConfig;
use vss_publisher::mapping::Mapper;
use vss_publisher::publisher::{zenoh_transport, VssPublisher};

/// Subscribes to the AZ3166 MQTT topic, maps `temperature_degC` to VSS and
/// publishes it over uProtocol (Zenoh), with `counter` as an extra field.
#[derive(Parser)]
struct Args {
    /// Configuration (TOML). Built-in defaults are used if omitted.
    #[arg(short, long)]
    config: Option<PathBuf>,
    /// MQTT broker host, overrides `mqtt.host`.
    #[arg(long)]
    mqtt_host: Option<String>,
    /// Zenoh configuration (JSON5), overrides `uprotocol.zenoh_config`.
    #[arg(long)]
    zenoh_config: Option<String>,
    /// Correlation ID added to every sample (e.g. test-run ID).
    #[arg(long)]
    correlation_id: Option<String>,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    init_logging();
    let args = Args::parse();

    // Configuration: TOML file or built-in defaults; command line flags win.
    let mut cfg = match &args.config {
        Some(path) => PublisherConfig::load(path)?,
        None => PublisherConfig::default(),
    };
    if let Some(host) = args.mqtt_host {
        cfg.mqtt.host = host;
    }
    if args.zenoh_config.is_some() {
        cfg.uprotocol.zenoh_config = args.zenoh_config;
    }

    // Output side: uProtocol transport over Zenoh, and the publisher that
    // knows our topic (//vehicle/8001/1/8001).
    let transport = zenoh_transport(
        &cfg.uprotocol.authority,
        cfg.uprotocol.zenoh_config.as_deref(),
    )
    .await?;
    let publisher = VssPublisher::new(transport, &cfg.uprotocol);
    let mapper = Mapper::new(cfg.mapping.clone(), args.correlation_id);

    // Input side: MQTT client. rumqttc splits it in two halves:
    // - `client` sends requests (subscribe, publish) to the broker;
    // - `eventloop` must be polled continuously; it keeps the connection
    //   alive and yields everything the broker sends us.
    let mqtt = &cfg.mqtt;
    let mut options = MqttOptions::new(&mqtt.client_id, &mqtt.host, mqtt.port);
    options.set_keep_alive(Duration::from_secs(mqtt.keep_alive_s));
    let (client, mut eventloop) = AsyncClient::new(options, 16);
    info!(
        mqtt = %format!("{}:{}/{}", mqtt.host, mqtt.port, mqtt.topic),
        uprotocol = %publisher.topic().to_uri(false),
        vss = %cfg.mapping.vss_path,
        "VSS uProtocol publisher started"
    );

    let shutdown = shutdown_signal();
    tokio::pin!(shutdown);
    // Main loop: wait for the next MQTT event (or shutdown) and handle it.
    loop {
        let event = tokio::select! {
            event = eventloop.poll() => event,
            _ = &mut shutdown => break,
        };
        match event {
            // Clean session: subscribe again after every (re)connect.
            // (ConnAck = the broker accepted our connection.)
            Ok(Event::Incoming(Packet::ConnAck(_))) => {
                info!("connected to MQTT broker");
                // QoS 1 = at least once: the broker re-sends until we
                // acknowledge, so a reading can arrive twice (see mapping.rs).
                if let Err(e) = client.try_subscribe(&mqtt.topic, QoS::AtLeastOnce) {
                    warn!("MQTT subscribe failed: {e}");
                }
            }
            // A reading from the board: MQTT payload -> VssSample -> uMessage.
            Ok(Event::Incoming(Packet::Publish(p))) => match mapper.map(&p.payload) {
                Ok(sample) => {
                    debug!(?sample, "publish");
                    if let Err(e) = publisher.publish(&sample).await {
                        warn!("uProtocol publish failed: {e}");
                    }
                }
                // Unusable payload: log and skip. The Guardian notices the
                // gap itself (no fresh sample -> TempSourceConnectionLost).
                Err(e) => warn!(mqtt_topic = %p.topic, "reading dropped: {e}"),
            },
            // Everything else (pings, acks, our own outgoing packets): nothing to do.
            Ok(_) => {}
            // Broker unreachable or connection lost. The next poll() reconnects;
            // wait a moment so we do not retry in a tight loop.
            Err(e) => {
                warn!("MQTT connection error: {e}; retrying in 1 s");
                tokio::time::sleep(Duration::from_secs(1)).await;
            }
        }
    }
    info!("VSS uProtocol publisher stopping");
    Ok(())
}

/// Ctrl-C or SIGTERM (sent by Podman / Ankaios when a workload is stopped).
async fn shutdown_signal() {
    let mut term = tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
        .expect("cannot install SIGTERM handler");
    tokio::select! {
        _ = tokio::signal::ctrl_c() => {}
        _ = term.recv() => {}
    }
}

/// Logs to stderr; level from RUST_LOG (default info, Zenoh only warnings).
/// `RUST_LOG=debug` shows every published sample.
fn init_logging() {
    let filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info,zenoh=warn"));
    tracing_subscriber::fmt()
        .with_env_filter(filter)
        .with_writer(std::io::stderr)
        .with_ansi(std::io::IsTerminal::is_terminal(&std::io::stderr()))
        .init();
}
