/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! MQTT reading -> VSS sample. Pure, no I/O.
//!
//! The device payload is a JSON object. Two keys are used, both configurable
//! in `[mapping]`: the temperature (`temperature_degC`) and the rolling counter
//! (`counter`). All other keys (pressure, humidity, acceleration, ...) are
//! ignored. Numbers may also be sent as numeric strings.
//!
//! The sample time the Guardian needs is in the uMessage: its UUIDv7 id
//! records when the publisher created it (publisher.rs).
//!
//! The mapper does not judge plausibility: an implausible temperature is
//! forwarded as is, because detecting it is the Guardian's job.
//!
//! Flow step 3 in `lib.rs`. Example:
//!
//! ```text
//! MQTT in : {"pressure_hPa": 1215.87, "temperature_degC": 24.65,
//!            "humidity_perc": 54.11, ..., "counter": 31}
//! VSS out : {"path": "Vehicle.Powertrain.TractionBattery.Temperature.Max",
//!            "value": 24.65, "seq": 9, "rolling_counter": 31}
//! ```

use std::fmt;

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use crate::config::MappingConfig;

/// Guardian input payload (see battery-thermal-guardian/src/contract.rs). Field names and
/// types are the contract; keep both sides in sync.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VssSample {
    /// VSS signal name.
    pub path: String,
    /// Temperature in Celsius, exactly as the board sent it.
    pub value: f64,
    /// Our own sequence number (see `Mapper::map` for how it advances).
    pub seq: u64,
    /// The board's rolling counter, passed through unchanged.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rolling_counter: Option<u64>,
    /// Test-run ID from `--correlation-id`, if given.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
}

/// Why a payload could not be mapped (the reading is then dropped and logged).
#[derive(Debug, Clone, PartialEq)]
pub enum MappingError {
    InvalidJson(String),
    MissingField(String),
    NotANumber(String, String),
    NotACounter(String, String),
}

// Human-readable messages for the log.
impl fmt::Display for MappingError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            MappingError::InvalidJson(e) => write!(f, "payload is not a JSON object: {e}"),
            MappingError::MissingField(name) => write!(f, "field `{name}` missing"),
            MappingError::NotANumber(name, v) => write!(f, "field `{name}` is not a number: {v}"),
            MappingError::NotACounter(name, v) => {
                write!(f, "field `{name}` is not a non-negative integer: {v}")
            }
        }
    }
}

impl std::error::Error for MappingError {}

/// Turns MQTT payloads into VSS samples. Keeps a little state between
/// messages to assign sequence numbers.
pub struct Mapper {
    cfg: MappingConfig,
    correlation_id: Option<String>,
    /// seq of the last produced sample.
    seq: u64,
    /// Rolling counter of the last mapped reading.
    last_counter: Option<u64>,
}

impl Mapper {
    pub fn new(cfg: MappingConfig, correlation_id: Option<String>) -> Self {
        Self {
            cfg,
            correlation_id,
            seq: 0,
            last_counter: None,
        }
    }

    /// Maps one MQTT payload.
    pub fn map(&mut self, payload: &[u8]) -> Result<VssSample, MappingError> {
        // 1. Parse: must be a JSON object. Values are kept as raw JSON and
        //    converted by hand, so `24.65` and `"24.65"` are both accepted
        //    and every problem gets a clear error message.
        let reading: Map<String, Value> = serde_json::from_slice(payload)
            .map_err(|e| MappingError::InvalidJson(e.to_string()))?;

        // 2. Extract and convert the two keys we use (names from the config).
        let temp_key = &self.cfg.temperature_field;
        let value = number(temp_key, field(&reading, temp_key)?)?;
        let counter_key = &self.cfg.counter_field;
        let counter = rolling_counter(counter_key, field(&reading, counter_key)?)?;

        // 3. Sequence number.
        // A repeated counter is a re-delivery (e.g. MQTT QoS 1 retry) or a
        // frozen device: keep the sequence number so the Guardian sees a
        // duplicate instead of fresh data. Any other value, including the
        // wrap-around of the counter, is a new reading.
        if self.last_counter != Some(counter) {
            self.seq += 1;
            self.last_counter = Some(counter);
        }

        // 4. Build the VSS sample (the uMessage is built in publisher.rs).
        Ok(VssSample {
            path: self.cfg.vss_path.clone(),
            value,
            seq: self.seq,
            rolling_counter: Some(counter),
            correlation_id: self.correlation_id.clone(),
        })
    }
}

/// Value of `key`; a missing key and JSON `null` both count as missing.
fn field<'a>(reading: &'a Map<String, Value>, key: &str) -> Result<&'a Value, MappingError> {
    reading
        .get(key)
        .filter(|v| !v.is_null())
        .ok_or_else(|| MappingError::MissingField(key.to_string()))
}

/// JSON number or numeric string -> finite f64 ("NaN"/"inf" are rejected).
fn number(key: &str, v: &Value) -> Result<f64, MappingError> {
    let n = match v {
        Value::Number(n) => n.as_f64(),
        Value::String(s) => s.trim().parse::<f64>().ok(),
        _ => None,
    };
    n.filter(|n| n.is_finite())
        .ok_or_else(|| MappingError::NotANumber(key.to_string(), v.to_string()))
}

/// JSON number or numeric string -> non-negative integer (-1 and 1.5 are rejected).
fn rolling_counter(key: &str, v: &Value) -> Result<u64, MappingError> {
    let n = match v {
        Value::Number(n) => n.as_u64(),
        Value::String(s) => s.trim().parse::<u64>().ok(),
        _ => None,
    };
    n.ok_or_else(|| MappingError::NotACounter(key.to_string(), v.to_string()))
}
