/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! uProtocol side: wraps VSS samples into uMessages and publishes them.
//!
//! Flow step 4 in `lib.rs`. Same pattern as the Guardian's output: build a
//! PUBLISH uMessage with a JSON payload and hand it to the transport.

use std::sync::Arc;

use up_rust::{
    LocalUriProvider, StaticUriProvider, UCode, UMessageBuilder, UPayloadFormat, UStatus,
    UTransport, UUri,
};
use up_transport_zenoh::{zenoh_config, UPTransportZenoh};

use crate::config::UProtocolConfig;
use crate::mapping::VssSample;

/// Publishes VSS samples on one fixed uProtocol topic.
pub struct VssPublisher {
    /// Any uProtocol transport: Zenoh in main.rs, LocalTransport in tests.
    transport: Arc<dyn UTransport>,
    /// Our topic, e.g. //vehicle/8001/1/8001. The Guardian's input filter
    /// (//*/8001/1/8001) matches it.
    topic: UUri,
}

impl VssPublisher {
    pub fn new(transport: Arc<dyn UTransport>, cfg: &UProtocolConfig) -> Self {
        // //<authority>/<entity_id>/<version>/<resource_id>
        let topic =
            StaticUriProvider::new(cfg.authority.clone(), cfg.entity_id, cfg.entity_version)
                .get_resource_uri(cfg.resource_id);
        Self { transport, topic }
    }

    pub fn topic(&self) -> &UUri {
        &self.topic
    }

    /// Sample -> JSON -> PUBLISH uMessage -> transport.
    pub async fn publish(&self, sample: &VssSample) -> Result<(), UStatus> {
        let payload = serde_json::to_vec(sample)
            .map_err(|e| UStatus::fail_with_code(UCode::INTERNAL, e.to_string()))?;
        // The builder fills in the uProtocol attributes: type PUBLISH, a new
        // message ID (UUIDv7), source = our topic, payload format JSON. The
        // UUIDv7 contains the current time in ms; the Guardian uses it as the
        // sample time.
        let msg = UMessageBuilder::publish(self.topic.clone())
            .build_with_payload(payload, UPayloadFormat::UPAYLOAD_FORMAT_JSON)
            .map_err(|e| UStatus::fail_with_code(UCode::INTERNAL, e.to_string()))?;
        self.transport.send(msg).await
    }
}

/// Opens a uProtocol transport over Zenoh (same as in the Guardian).
/// Without a Zenoh config file Zenoh runs in peer mode and finds the
/// Guardian on the network by multicast scouting.
pub async fn zenoh_transport(
    authority: &str,
    zenoh_config_path: Option<&str>,
) -> Result<Arc<UPTransportZenoh>, Box<dyn std::error::Error + Send + Sync>> {
    let config = match zenoh_config_path {
        Some(path) => zenoh_config::Config::from_file(path)?,
        None => zenoh_config::Config::default(),
    };
    let transport = UPTransportZenoh::builder(authority)?
        .with_config(config)
        .build()
        .await?;
    Ok(Arc::new(transport))
}
