/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! Guardian configuration, loaded from TOML. Every field has a default, so a
//! config file only needs to contain what differs.
//!
//! The TOML sections map 1:1 to the structs below: `[uprotocol]` ->
//! `UProtocolConfig`, `[signal]` -> `SignalConfig`, `[thermal]` ->
//! `ThermalConfig`, `[dfm]` -> `DfmConfig`. See config/guardian.toml for a
//! file with all defaults.
//!
//! `#[serde(default)]` fills missing fields from the `Default` impl;
//! `deny_unknown_fields` turns a typo in the file into an error instead of a
//! silently ignored setting.

use serde::Deserialize;
use std::path::{Path, PathBuf};

use crate::contract::VSS_BATTERY_TEMPERATURE_MAX;

/// Complete configuration, as passed to `service::run` and `Guardian::new`.
#[derive(Debug, Clone, Default, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct GuardianConfig {
    pub uprotocol: UProtocolConfig,
    pub signal: SignalConfig,
    pub thermal: ThermalConfig,
    pub dfm: DfmConfig,
}

/// Addressing and timing of the uProtocol side (used by service.rs).
#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct UProtocolConfig {
    /// uProtocol authority (device) name of the Guardian.
    pub authority: String,
    /// uEntity ID of the Guardian.
    pub entity_id: u32,
    pub entity_version: u8,
    /// Topic filter for the VSS input, e.g. `//*/8001/1/8001`.
    pub input_topic: String,
    /// VSS path the Guardian evaluates; samples for other paths are ignored.
    pub vss_path: String,
    pub heartbeat_period_ms: u64,
    /// Period of the supervision tick (stale detection, mitigation timeout).
    pub tick_period_ms: u64,
    /// Optional Zenoh configuration file (JSON5).
    pub zenoh_config: Option<String>,
}

impl Default for UProtocolConfig {
    fn default() -> Self {
        Self {
            authority: "vehicle".into(),
            // Service IDs from the vendor range 0x8000-0xFFFE (uProtocol up-l3):
            // VSS publisher = 0x8001, Guardian = 0x8002; instance 0.
            entity_id: 0x8002,
            entity_version: 1,
            input_topic: "//*/8001/1/8001".into(),
            vss_path: VSS_BATTERY_TEMPERATURE_MAX.into(),
            heartbeat_period_ms: 1000,
            tick_period_ms: 100,
            zenoh_config: None,
        }
    }
}

/// Plausibility and freshness checks of the input signal.
// Used by signal.rs. Each field corresponds to one fault kind in contract.rs.
#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct SignalConfig {
    /// Plausible range; values outside raise TempOutOfRange.
    pub min_c: f64,
    pub max_c: f64,
    /// No accepted sample for this long raises TempSourceConnectionLost.
    pub stale_timeout_ms: u64,
    /// Samples older than this on arrival are rejected (TransportDelay).
    pub max_latency_ms: u64,
    /// Rate of change above this is treated as a spike unless confirmed.
    pub max_rate_c_per_s: f64,
    /// Consecutive samples needed to confirm a fast change as genuine.
    pub spike_confirm_samples: u32,
    /// Unchanged value for this long raises TempSignalStuck (0 disables).
    pub stuck_window_ms: u64,
    /// Changes smaller than this count as "unchanged".
    pub stuck_epsilon_c: f64,
    /// Consecutive accepted samples that clear a per-sample fault.
    pub heal_samples: u32,
    /// Consecutive accepted samples required before the signal is trusted.
    pub trust_samples: u32,
    /// Number of values of the device's rolling counter: it counts
    /// 0..counter_modulus-1 and then starts at 0 again (256 = 8-bit counter).
    pub counter_modulus: u64,
}

impl Default for SignalConfig {
    fn default() -> Self {
        Self {
            // Typical range of an NTC cell temperature sensor.
            min_c: -40.0,
            max_c: 150.0,
            stale_timeout_ms: 3000,
            max_latency_ms: 1000,
            max_rate_c_per_s: 10.0,
            spike_confirm_samples: 2,
            stuck_window_ms: 30_000,
            // 0.0 = only exactly identical values count as "stuck".
            stuck_epsilon_c: 0.0,
            heal_samples: 5,
            trust_samples: 3,
            counter_modulus: 256,
        }
    }
}

/// Thermal risk thresholds of the state machine.
// Used by guardian.rs (evaluate_thermal). Diagram of the state machine:
// Docs/battery-thermal-guardian.md.
#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ThermalConfig {
    /// MONITORING -> WARNING at or above this temperature.
    pub warning_c: f64,
    /// Temperature that, if held for `critical_persist_ms`, means CRITICAL.
    pub critical_c: f64,
    /// Safety margin before a state is left again: WARNING ends below
    /// `warning_c - hysteresis_c`, MITIGATING counts as improved below
    /// `critical_c - hysteresis_c`. Prevents flickering at a threshold.
    pub hysteresis_c: f64,
    /// Temperature rise rate that alone is enough for WARNING.
    pub warning_rate_c_per_s: f64,
    /// Window over which the rise rate is computed.
    pub trend_window_ms: u64,
    /// How long temperature must stay >= critical_c before CRITICAL.
    pub critical_persist_ms: u64,
    /// Mitigation that does not improve the condition within this time has failed.
    pub mitigation_timeout_ms: u64,
    /// How long the improved condition must hold before mitigation is released.
    pub recovery_hold_ms: u64,
}

impl Default for ThermalConfig {
    fn default() -> Self {
        Self {
            warning_c: 55.0,
            critical_c: 65.0,
            hysteresis_c: 3.0,
            warning_rate_c_per_s: 0.5,
            trend_window_ms: 10_000,
            critical_persist_ms: 2000,
            mitigation_timeout_ms: 30_000,
            recovery_hold_ms: 5000,
        }
    }
}

/// Reporting of catalog faults to the Diagnostic Fault Manager (used by dfm.rs).
#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct DfmConfig {
    /// DFM fault catalog (JSON), the same file the DFM loads. Not set = no
    /// DFM reporting; faults are still published over uProtocol.
    pub catalog: Option<PathBuf>,
    /// How often to retry connecting while the DFM is not reachable.
    pub retry_period_ms: u64,
}

impl Default for DfmConfig {
    fn default() -> Self {
        Self {
            catalog: None,
            retry_period_ms: 5000,
        }
    }
}

impl GuardianConfig {
    /// Parses TOML text and validates the result.
    pub fn from_toml_str(s: &str) -> Result<Self, String> {
        let cfg: GuardianConfig = toml::from_str(s).map_err(|e| e.to_string())?;
        cfg.validate()?;
        Ok(cfg)
    }

    /// Reads and parses a TOML file (used by all three binaries).
    pub fn load(path: &Path) -> Result<Self, String> {
        let text = std::fs::read_to_string(path)
            .map_err(|e| format!("cannot read {}: {e}", path.display()))?;
        Self::from_toml_str(&text)
    }

    /// Rejects combinations that would make the state machine meaningless
    /// (e.g. warning above critical) or would divide by / loop on zero.
    pub fn validate(&self) -> Result<(), String> {
        let s = &self.signal;
        let t = &self.thermal;
        if s.min_c >= s.max_c {
            return Err("signal.min_c must be below signal.max_c".into());
        }
        if t.warning_c >= t.critical_c {
            return Err("thermal.warning_c must be below thermal.critical_c".into());
        }
        if t.hysteresis_c < 0.0 {
            return Err("thermal.hysteresis_c must not be negative".into());
        }
        if s.trust_samples == 0 || s.heal_samples == 0 || s.spike_confirm_samples == 0 {
            return Err("signal.*_samples values must be at least 1".into());
        }
        // At least 4 values, so that "newer" (less than half the range ahead)
        // and "older" can be told apart.
        if s.counter_modulus < 4 {
            return Err("signal.counter_modulus must be at least 4".into());
        }
        if s.stale_timeout_ms == 0 || self.uprotocol.tick_period_ms == 0 {
            return Err("stale_timeout_ms and tick_period_ms must be positive".into());
        }
        if self.uprotocol.heartbeat_period_ms == 0 {
            return Err("uprotocol.heartbeat_period_ms must be positive".into());
        }
        if self.dfm.retry_period_ms == 0 {
            return Err("dfm.retry_period_ms must be positive".into());
        }
        Ok(())
    }
}
