/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! Service contract of the Battery Thermal Guardian.
//!
//! Everything another component needs to agree on lives here: the VSS input
//! payload, the uProtocol resource IDs of the Guardian's topics and the JSON
//! payloads of the heartbeat, state, fault and mitigation events.
//! All payloads are sent as `UPAYLOAD_FORMAT_JSON`.
//!
//! Reading guide: the structs here are plain data. `Serialize`/`Deserialize`
//! (serde) turn them into JSON and back, field names become JSON keys.
//! `#[serde(rename_all = "SCREAMING_SNAKE_CASE")]` makes enum values appear
//! as e.g. `"TempSourceConnectionLost"` in JSON. Fields marked
//! `skip_serializing_if = "Option::is_none"` are left out of the JSON when
//! they are `None`, and `default` lets them be missing when reading.

use serde::{Deserialize, Serialize};

/// Default VSS signal evaluated by the Guardian: float sensor, Celsius,
/// "temperature of the hottest cell". Defined in COVESA VSS
/// spec/Powertrain/TractionBattery.vspec (v4.0: Battery.vspec), present in v4.0 to v6.1.
pub const VSS_BATTERY_TEMPERATURE_MAX: &str = "Vehicle.Powertrain.TractionBattery.Temperature.Max";

/// uProtocol resource IDs of the topics published by the Guardian uEntity.
// Full topic = //<authority>/<entity_id>/<version>/<resource>, e.g. with the
// defaults the fault topic is //vehicle/8002/1/8003. Resource IDs 0x8000 and
// above are reserved for published topics in uProtocol.
pub mod resource {
    pub const HEARTBEAT: u16 = 0x8001;
    pub const STATE: u16 = 0x8002;
    pub const FAULT: u16 = 0x8003;
    pub const MITIGATION: u16 = 0x8004;
}

// ------------------------------------------------------------------ input

/// One VSS datapoint as published by the VSS uProtocol publisher.
///
/// The sample time is the creation time of the uMessage that carries it,
/// which uProtocol stores in the UUIDv7 message id (read with
/// `UUID::get_time()` in service.rs).
// This is the payload of every uMessage on the input topic. The publisher
// (vss-uprotocol-publisher/src/mapping.rs) has its own copy of this struct;
// both must stay identical.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VssSample {
    /// Full VSS path, e.g. `Vehicle.Powertrain.TractionBattery.Temperature.Max`.
    pub path: String,
    /// Value in the VSS unit of the signal (celsius for temperatures).
    pub value: f64,
    /// Rolling (alive) counter of the source device: +1 per reading, back to
    /// 0 after `signal.counter_modulus - 1` (255 for the AZ3166).
    // Used to detect duplicates, reordering and lost readings (see signal.rs).
    pub rolling_counter: u64,
    /// Optional campaign / test-run identifier, echoed in every event it triggers.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
}

// ------------------------------------------------------------------ states and faults

/// States of the Guardian state machine (transitions: see guardian.rs).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum GuardianState {
    /// Started, no trusted signal yet.
    Clear,
    /// Trusted signal, thermal condition nominal.
    Monitoring,
    /// Temperature threshold or rise-rate exceeded.
    Warning,
    /// Dangerous temperature persisted.
    Critical,
    /// Mitigation requested, waiting for the condition to improve.
    Mitigating,
    /// Signal untrusted (stale or stuck): thermal risk cannot be ruled out.
    Degraded,
}

/// Everything that can be wrong with the input (detected in signal.rs).
///
/// The first four are the faults of the DFM fault catalog
/// `dfm-container/battery_guardian_catalog.json` (catalog id "battery");
/// their variant names are the catalog's `name` and `catalog_id()` returns
/// the catalog's `id`.
/// The transport faults are Guardian-internal: published on the uProtocol
/// fault topic like the others, but not part of the catalog, so they are not
/// forwarded to the DFM.
// Ord is derived so faults can be kept in a sorted map (stable output order).
// No serde rename: in JSON the fault appears exactly as the catalog `name`,
// e.g. "TempSignalStuck".
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub enum FaultKind {
    /// No accepted sample within the stale timeout (source dropout, e.g.
    /// Wi-Fi/MQTT link to the AZ3166 lost).
    TempSourceConnectionLost,
    /// Value has not changed for longer than the stuck window.
    TempSignalStuck,
    /// Value outside the physically plausible range.
    TempOutOfRange,
    /// Implausible rate of change that was not confirmed by the next sample.
    TempSignalSpike,
    /// Sample arrived later than the allowed end-to-end latency.
    TransportDelay,
    /// Sample with an already seen sequence number.
    TransportDuplicate,
    /// Sample older than one already received.
    TransportOutOfOrder,
    /// Payload could not be decoded according to this contract.
    PayloadInvalid,
}

/// Fault classes as named in the challenge README ("Fault Classes to Cover").
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum FaultClass {
    Source,
    Signal,
    Transport,
}

impl FaultKind {
    /// Every fault kind, e.g. for building a fault catalog.
    pub const ALL: [FaultKind; 8] = [
        FaultKind::TempSourceConnectionLost,
        FaultKind::TempSignalStuck,
        FaultKind::TempOutOfRange,
        FaultKind::TempSignalSpike,
        FaultKind::TransportDelay,
        FaultKind::TransportDuplicate,
        FaultKind::TransportOutOfOrder,
        FaultKind::PayloadInvalid,
    ];

    /// Fault id in the DFM catalog `battery_guardian_catalog.json`, or `None`
    /// for Guardian-internal faults that are not reported to the DFM.
    // dfm.rs reports exactly the faults with Some(id) to the DFM, using this id.
    pub fn catalog_id(self) -> Option<&'static str> {
        match self {
            FaultKind::TempSourceConnectionLost => Some("btg.src.connection_lost"),
            FaultKind::TempSignalStuck => Some("btg.temp.stuck"),
            FaultKind::TempOutOfRange => Some("btg.temp.out_of_range"),
            FaultKind::TempSignalSpike => Some("btg.temp.spike"),
            FaultKind::TransportDelay
            | FaultKind::TransportDuplicate
            | FaultKind::TransportOutOfOrder
            | FaultKind::PayloadInvalid => None,
        }
    }

    pub fn class(self) -> FaultClass {
        match self {
            FaultKind::TempSourceConnectionLost => FaultClass::Source,
            FaultKind::TempSignalStuck | FaultKind::TempOutOfRange | FaultKind::TempSignalSpike => {
                FaultClass::Signal
            }
            FaultKind::TransportDelay
            | FaultKind::TransportDuplicate
            | FaultKind::TransportOutOfOrder
            | FaultKind::PayloadInvalid => FaultClass::Transport,
        }
    }

    /// Faults that make the temperature signal untrusted as a whole.
    /// All other faults only cause the offending sample to be discarded.
    // While one of these is active the Guardian cannot judge the thermal
    // situation -> state DEGRADED (see Guardian::sync_with_signal).
    pub fn disarms_signal(self) -> bool {
        matches!(
            self,
            FaultKind::TempSourceConnectionLost | FaultKind::TempSignalStuck
        )
    }
}

/// A fault is reported twice: once when it appears, once when it is gone.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum FaultStatus {
    Raised,
    Cleared,
}

/// What the Guardian asks the vehicle to do. The Guardian only *requests*;
/// carrying it out is up to whoever subscribes to the mitigation topic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum MitigationAction {
    /// Level 1 in CRITICAL: derate charge/discharge power, maximum cooling.
    ReducePowerMaxCooling,
    /// Level 2 after failed mitigation: warn occupants to leave the vehicle.
    OccupantEvacuationWarning,
    /// Fallback in DEGRADED: tell the driver battery monitoring is unavailable, limit power.
    MonitoringUnavailableWarning,
}

/// A mitigation is reported when it is requested and when it is lifted again.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum MitigationStatus {
    Requested,
    Released,
}

// ------------------------------------------------------------------ output events

/// Reference to the input sample (and uProtocol message) that triggered an event.
// This is the evidence link: from any fault / state / mitigation event you can
// go back to the exact input message (message_id) and test run (correlation_id).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SampleRef {
    pub rolling_counter: u64,
    /// When the publisher created the uMessage (from its UUIDv7 id), ms since epoch.
    pub sent_ms: u64,
    pub value: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
}

/// Published on the STATE topic whenever the state machine changes state.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StateEvent {
    /// Guardian-wide event number; orders events across topics.
    pub seq: u64,
    pub from: GuardianState,
    pub to: GuardianState,
    /// Human-readable cause, e.g. "temperature 68.1 C >= 65 C for 2000 ms".
    pub reason: String,
    /// Guardian time when the transition happened, ms since epoch.
    pub at_ms: u64,
    /// The sample that caused it; `None` for time-driven transitions (tick).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger: Option<SampleRef>,
}

/// Published on the FAULT topic when a fault is raised or cleared.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FaultEvent {
    /// Guardian-wide event number; orders events across topics.
    pub seq: u64,
    pub fault: FaultKind,
    /// DFM catalog id (e.g. "btg.temp.stuck"); `null` for Guardian-internal
    /// faults that are not in the catalog and not forwarded to the DFM.
    pub catalog_id: Option<String>,
    pub class: FaultClass,
    pub status: FaultStatus,
    pub detail: String,
    /// Guardian state after the fault was processed.
    pub state: GuardianState,
    /// Guardian time when the fault was raised or cleared, ms since epoch.
    pub at_ms: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger: Option<SampleRef>,
}

/// Published on the MITIGATION topic when a mitigation is requested or released.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MitigationEvent {
    /// Guardian-wide event number; orders events across topics.
    pub seq: u64,
    pub action: MitigationAction,
    pub status: MitigationStatus,
    pub reason: String,
    /// Guardian time when the mitigation was requested or released, ms since epoch.
    pub at_ms: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger: Option<SampleRef>,
}

/// Input statistics, reported in the heartbeat.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Counters {
    /// Samples (and invalid payloads) that reached the Guardian.
    pub received: u64,
    /// Samples that passed all checks.
    pub accepted: u64,
    /// Samples discarded by a check (each one raised or refreshed a fault).
    pub rejected: u64,
    /// Readings missing according to gaps in the rolling counter.
    pub missing: u64,
}

/// Published on the HEARTBEAT topic every `heartbeat_period_ms`.
// Two purposes: (1) proof that the Guardian itself is alive (a consumer that
// stops seeing heartbeats knows the Guardian is down), (2) a status snapshot.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Heartbeat {
    /// Heartbeat counter (separate from the event `seq`).
    pub seq: u64,
    pub state: GuardianState,
    /// Guardian time when the heartbeat was built, ms since epoch.
    pub at_ms: u64,
    pub uptime_ms: u64,
    /// Last accepted temperature, if any.
    pub temperature_c: Option<f64>,
    /// Device rolling counter of the same (last accepted) sample.
    pub rolling_counter: Option<u64>,
    /// Time since the last accepted sample, if any.
    pub signal_age_ms: Option<u64>,
    pub active_faults: Vec<FaultKind>,
    pub active_mitigations: Vec<MitigationAction>,
    pub counters: Counters,
}

/// Event emitted by the Guardian core; each variant maps to one topic.
// The core returns a Vec<GuardianEvent> for every step; service.rs publishes
// each one on the topic given by resource_id().
#[derive(Debug, Clone, PartialEq)]
pub enum GuardianEvent {
    State(StateEvent),
    Fault(FaultEvent),
    Mitigation(MitigationEvent),
}

impl GuardianEvent {
    /// Topic (resource ID) this event is published on.
    pub fn resource_id(&self) -> u16 {
        match self {
            GuardianEvent::State(_) => resource::STATE,
            GuardianEvent::Fault(_) => resource::FAULT,
            GuardianEvent::Mitigation(_) => resource::MITIGATION,
        }
    }

    pub fn seq(&self) -> u64 {
        match self {
            GuardianEvent::State(e) => e.seq,
            GuardianEvent::Fault(e) => e.seq,
            GuardianEvent::Mitigation(e) => e.seq,
        }
    }

    // Mutable access to the seq field, whatever the variant.
    fn seq_mut(&mut self) -> &mut u64 {
        match self {
            GuardianEvent::State(e) => &mut e.seq,
            GuardianEvent::Fault(e) => &mut e.seq,
            GuardianEvent::Mitigation(e) => &mut e.seq,
        }
    }

    /// Numbers events consecutively, continuing from `last_seq`.
    // Events are created with seq 0 and numbered at the end of each step
    // (Guardian::finish). Zenoh does not keep the order between different
    // topics, so consumers sort by this number to get the true order.
    pub fn number(events: &mut [GuardianEvent], last_seq: &mut u64) {
        for event in events {
            *last_seq += 1;
            *event.seq_mut() = *last_seq;
        }
    }

    /// JSON payload of the inner event (without the enum wrapper).
    pub fn to_json(&self) -> serde_json::Result<Vec<u8>> {
        match self {
            GuardianEvent::State(e) => serde_json::to_vec(e),
            GuardianEvent::Fault(e) => serde_json::to_vec(e),
            GuardianEvent::Mitigation(e) => serde_json::to_vec(e),
        }
    }
}
