/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! DFM reporter: forwards catalog faults to the Eclipse OpenSOVD Diagnostic
//! Fault Manager (flow step 6 in `lib.rs`).
//!
//! The DFM side (fault-lib reporters) is in faults.rs. This file connects it
//! to the Guardian:
//!
//! - maps the Guardian's `FaultKind` to faults.rs' `GuardianFault`; the four
//!   catalog faults have one, the transport faults are not in the catalog;
//! - turns fault events into `GuardianFaults::set`: RAISED = active
//!   (`Failed`), CLEARED = not active (`Passed`);
//! - runs faults.rs on its own thread. Connecting blocks until the DFM
//!   answers the catalog handshake and fails if the DFM is not running, but
//!   the Guardian must keep working without the DFM. So the service loop only
//!   puts reports into a channel; the thread retries every `retry_period_ms`
//!   and keeps the latest state of each fault until it is connected, then
//!   reports those so the DFM catches up with the current state.

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::sync::mpsc::{self, Receiver, RecvTimeoutError, Sender};
use std::thread;
use std::time::{Duration, Instant};

use fault_lib::catalog::FaultCatalogBuilder;
use tracing::{debug, info, warn};

use crate::config::DfmConfig;
use crate::contract::{FaultEvent, FaultKind, FaultStatus};
use crate::faults::{GuardianFault, GuardianFaults};

/// The faults.rs fault for a Guardian fault, `None` if it is not in the DFM catalog.
pub fn dfm_fault(kind: FaultKind) -> Option<GuardianFault> {
    match kind {
        FaultKind::TempSourceConnectionLost => Some(GuardianFault::ConnectionLost),
        FaultKind::TempOutOfRange => Some(GuardianFault::OutOfRange),
        FaultKind::TempSignalStuck => Some(GuardianFault::Stuck),
        FaultKind::TempSignalSpike => Some(GuardianFault::Spike),
        FaultKind::TransportDelay
        | FaultKind::TransportDuplicate
        | FaultKind::TransportOutOfOrder
        | FaultKind::PayloadInvalid => None,
    }
}

/// What to report for a fault event: the fault and whether it is now active.
pub fn to_report(event: &FaultEvent) -> Option<(GuardianFault, bool)> {
    let fault = dfm_fault(event.fault)?;
    Some((fault, event.status == FaultStatus::Raised))
}

/// Handle used by the service loop. Reporting never blocks.
pub struct DfmReporter {
    tx: Sender<(GuardianFault, bool)>,
}

impl DfmReporter {
    /// Starts the reporter thread. `Ok(None)` if no catalog is configured
    /// (DFM reporting off); an error if the catalog cannot be loaded.
    pub fn start(cfg: &DfmConfig) -> Result<Option<Self>, String> {
        let Some(catalog) = cfg.catalog.clone() else {
            return Ok(None);
        };
        // Load the catalog once now, so a wrong path or broken file stops the
        // Guardian at startup instead of only showing up in the DFM thread.
        FaultCatalogBuilder::new()
            .json_file(catalog.clone())
            .and_then(FaultCatalogBuilder::try_build)
            .map_err(|e| format!("cannot load DFM catalog {}: {e:?}", catalog.display()))?;

        let worker = Worker {
            catalog: catalog.clone(),
            retry_period: Duration::from_millis(cfg.retry_period_ms),
        };
        let (tx, rx) = mpsc::channel();
        thread::Builder::new()
            .name("dfm-reporter".into())
            .spawn(move || worker.run(rx))
            .map_err(|e| format!("cannot start DFM reporter thread: {e}"))?;
        info!(catalog = %catalog.display(), "DFM reporting enabled");
        Ok(Some(Self { tx }))
    }

    /// Queues the fault event for the DFM if it is a catalog fault.
    pub fn report(&self, event: &FaultEvent) {
        if let Some(report) = to_report(event) {
            // Only fails if the reporter thread is gone.
            let _ = self.tx.send(report);
        }
    }
}

/// The reporter thread: connects to the DFM and reports the fault states.
struct Worker {
    catalog: PathBuf,
    retry_period: Duration,
}

impl Worker {
    /// Runs until the `DfmReporter` (the sending side) is dropped.
    fn run(self, rx: Receiver<(GuardianFault, bool)>) {
        let mut faults: Option<GuardianFaults> = None;
        // Latest state per fault (by catalog id) while not connected.
        let mut pending: BTreeMap<&'static str, (GuardianFault, bool)> = BTreeMap::new();
        let mut next_attempt = Instant::now();
        loop {
            if faults.is_none() && Instant::now() >= next_attempt {
                match GuardianFaults::new(self.catalog.clone()) {
                    Ok(mut f) => {
                        info!("connected to DFM");
                        for (fault, active) in std::mem::take(&mut pending).into_values() {
                            f.set(fault, active);
                        }
                        faults = Some(f);
                    }
                    Err(e) => {
                        warn!("DFM not reachable, retry in {:?}: {e}", self.retry_period);
                        next_attempt = Instant::now() + self.retry_period;
                    }
                }
            }
            // Connected: wait for the next report. Not connected: wait at
            // most until the next connection attempt.
            let received = match &faults {
                Some(_) => rx.recv().map_err(|_| RecvTimeoutError::Disconnected),
                None => rx.recv_timeout(next_attempt.saturating_duration_since(Instant::now())),
            };
            match received {
                Ok((fault, active)) => match &mut faults {
                    // Reports only if the state changed (faults.rs).
                    Some(f) => f.set(fault, active),
                    None => {
                        pending.insert(fault.catalog_id(), (fault, active));
                    }
                },
                Err(RecvTimeoutError::Timeout) => {}
                Err(RecvTimeoutError::Disconnected) => break,
            }
        }
        // Dropping GuardianFaults disconnects from the DFM.
        debug!("DFM reporter stopped");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::contract::{FaultClass, GuardianState};

    fn event(fault: FaultKind, status: FaultStatus) -> FaultEvent {
        FaultEvent {
            seq: 1,
            fault,
            catalog_id: fault.catalog_id().map(str::to_string),
            class: FaultClass::Signal,
            status,
            detail: String::new(),
            state: GuardianState::Monitoring,
            at_ms: 0,
            trigger: None,
        }
    }

    // Every Guardian fault with a catalog id maps to the faults.rs fault with
    // the same id; faults without one are not reported.
    #[test]
    fn fault_kinds_map_to_catalog_faults() {
        for kind in FaultKind::ALL {
            let dfm_id = dfm_fault(kind).map(GuardianFault::catalog_id);
            assert_eq!(dfm_id, kind.catalog_id(), "{kind:?}");
        }
    }

    #[test]
    fn raised_is_active_and_cleared_is_not() {
        let raised = event(FaultKind::TempSignalStuck, FaultStatus::Raised);
        let cleared = event(FaultKind::TempSignalStuck, FaultStatus::Cleared);
        assert_eq!(to_report(&raised), Some((GuardianFault::Stuck, true)));
        assert_eq!(to_report(&cleared), Some((GuardianFault::Stuck, false)));
        let transport = event(FaultKind::TransportDuplicate, FaultStatus::Raised);
        assert_eq!(to_report(&transport), None);
    }
}
