/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! Guardian decision core (flow steps 3 and 4 in `lib.rs`).
//!
//! Pure and deterministic: no I/O, no clock access. Time is passed in by the
//! caller, so the same input sequence always yields the same events. This is
//! what makes fault campaigns replayable and the core unit-testable.
//!
//! State machine (README "Suggested Guardian Behavior", plus DEGRADED):
//!
//! ```text
//! CLEAR      -> MONITORING  trusted stream present
//! MONITORING -> WARNING     temperature >= warning_c or rise rate >= warning_rate
//! WARNING    -> MONITORING  temperature < warning_c - hysteresis and rate below limit
//! WARNING    -> CRITICAL    temperature >= critical_c for critical_persist_ms
//! CRITICAL   -> MITIGATING  mitigation requested (immediately)
//! MITIGATING -> MONITORING  temperature < critical_c - hysteresis for recovery_hold_ms
//! MITIGATING -> CRITICAL    no improvement within mitigation_timeout_ms (escalation)
//! CLEAR/MONITORING/WARNING -> DEGRADED   signal stale or stuck
//! DEGRADED   -> MONITORING  signal trusted again
//! ```
//!
//! CRITICAL and MITIGATING are latched when the signal is lost: an active
//! mitigation is never withdrawn because the evidence disappeared.
//!
//! # How a call is processed
//!
//! The three entry points (`on_sample`, `on_invalid_payload`, `on_tick`) all
//! follow the same pattern, called a "step":
//!
//! 1. ask the [`SignalMonitor`] what this input means (verdict + fault changes);
//! 2. `sync_with_signal`: go to / leave DEGRADED if the signal trust changed;
//! 3. (samples only) `evaluate_thermal`: run the thermal state machine;
//! 4. `finish`: turn fault changes into fault events, append the state and
//!    mitigation events collected in the `Step`, number them, return them.

use tracing::info;

use crate::config::GuardianConfig;
use crate::contract::{
    FaultEvent, GuardianEvent, GuardianState, Heartbeat, MitigationAction, MitigationEvent,
    MitigationStatus, SampleRef, StateEvent, VssSample,
};
use crate::signal::{FaultChange, SignalMonitor, Verdict};
use crate::thermal::Trend;

/// The Guardian: current state plus everything needed to decide the next one.
pub struct Guardian {
    cfg: GuardianConfig,
    /// Time the Guardian was created (for uptime and "no data since start").
    start_ms: u64,
    /// Current state of the state machine.
    state: GuardianState,
    /// Signal integrity checks; owns the fault list and input counters.
    signal: SignalMonitor,
    /// Recent accepted temperatures, for the rise rate.
    trend: Trend,
    /// Since when the temperature is continuously >= critical_c (in WARNING).
    critical_since_ms: Option<u64>,
    /// Since when the temperature is below the recovery level (in MITIGATING).
    improved_since_ms: Option<u64>,
    /// When the current mitigation was requested (for the timeout).
    mitigation_since_ms: Option<u64>,
    /// 0 = none, 1 = ReducePowerMaxCooling, 2 = OccupantEvacuationWarning.
    mitigation_level: u8,
    /// Mitigations currently requested (reported in the heartbeat).
    mitigations: Vec<MitigationAction>,
    /// Counter for heartbeats.
    heartbeat_seq: u64,
    /// Counter for state/fault/mitigation events (see GuardianEvent::number).
    event_seq: u64,
    /// Device rolling counter of the last accepted sample (for the heartbeat).
    last_rolling_counter: Option<u64>,
}

/// Collects the events of one processing step.
// Passed through all helper functions of one call, so each of them can add
// events. `trigger` is the sample being processed (None for ticks); every
// event created in this step references it.
struct Step<'a> {
    now_ms: u64,
    trigger: Option<&'a SampleRef>,
    events: Vec<GuardianEvent>,
}

impl Guardian {
    /// New Guardian in state CLEAR. `start_ms` is the current time.
    pub fn new(cfg: GuardianConfig, start_ms: u64) -> Self {
        Self {
            signal: SignalMonitor::new(cfg.signal.clone(), start_ms),
            trend: Trend::new(cfg.thermal.trend_window_ms),
            cfg,
            start_ms,
            state: GuardianState::Clear,
            critical_since_ms: None,
            improved_since_ms: None,
            mitigation_since_ms: None,
            mitigation_level: 0,
            mitigations: Vec::new(),
            heartbeat_seq: 0,
            event_seq: 0,
            last_rolling_counter: None,
        }
    }

    pub fn state(&self) -> GuardianState {
        self.state
    }

    pub fn active_mitigations(&self) -> &[MitigationAction] {
        &self.mitigations
    }

    /// Processes one VSS sample received over uProtocol.
    ///
    /// `sent_ms` is when the publisher created the uMessage, taken from its
    /// UUIDv7 message id; `message_id` is that id as text (for evidence).
    // Called by service.rs for every decoded input message.
    pub fn on_sample(
        &mut self,
        sample: &VssSample,
        sent_ms: u64,
        message_id: Option<String>,
        now_ms: u64,
    ) -> Vec<GuardianEvent> {
        // Not our signal (another VSS path on the same topic): ignore completely.
        if sample.path != self.cfg.uprotocol.vss_path {
            return Vec::new();
        }
        // Evidence link that every event of this step will carry.
        let trigger = SampleRef {
            rolling_counter: sample.rolling_counter,
            sent_ms,
            value: sample.value,
            message_id,
            correlation_id: sample.correlation_id.clone(),
        };

        // Step 1: can this sample be trusted? `changes` lists faults that were
        // raised or cleared by it (e.g. TransportDuplicate raised).
        let (verdict, changes) = self.signal.on_sample(sample, sent_ms, now_ms);

        let mut step = Step {
            now_ms,
            trigger: Some(&trigger),
            events: Vec::new(),
        };
        // Only accepted samples feed the trend and the heartbeat counter.
        if verdict == Verdict::Accepted {
            self.trend.push(sent_ms, sample.value);
            self.last_rolling_counter = Some(sample.rolling_counter);
        }

        // Step 2: react to signal trust (e.g. stuck cleared -> back to MONITORING).
        self.sync_with_signal(&mut step);

        // Step 3: thermal evaluation, only with a value we trust.
        if verdict == Verdict::Accepted && !self.signal.is_disarmed() {
            self.evaluate_thermal(sample.value, &mut step);
        }

        // Step 4: build and number the events.
        self.finish(changes, step)
    }

    /// Processes a uProtocol message whose payload is not a valid VSS sample.
    // Only produces a PayloadInvalid fault (and ends a connection loss: data
    // arrives again); the state does not change.
    pub fn on_invalid_payload(&mut self, detail: String, now_ms: u64) -> Vec<GuardianEvent> {
        let changes = self.signal.on_invalid_payload(detail, now_ms);
        let step = Step {
            now_ms,
            trigger: None,
            events: Vec::new(),
        };
        self.finish(changes, step)
    }

    /// Periodic supervision, independent of incoming samples.
    // Called by service.rs every tick_period_ms (100 ms). This is the only way
    // to notice that samples *stopped* arriving.
    pub fn on_tick(&mut self, now_ms: u64) -> Vec<GuardianEvent> {
        // A tick can raise TempSourceConnectionLost, or notice that no sample
        // was accepted for a while (persistent rejection).
        let was_disarmed = self.signal.is_disarmed();
        let changes = self.signal.on_tick(now_ms);
        let mut step = Step {
            now_ms,
            trigger: None,
            events: Vec::new(),
        };
        // Signal lost: old trend points are no longer meaningful.
        if !changes.is_empty() || (!was_disarmed && self.signal.is_disarmed()) {
            self.trend.clear();
        }
        // Signal lost -> maybe DEGRADED.
        self.sync_with_signal(&mut step);
        // A mitigation can fail even when no samples arrive.
        self.check_mitigation_timeout(&mut step);
        self.finish(changes, step)
    }

    /// Status snapshot, published by service.rs every heartbeat_period_ms.
    pub fn heartbeat(&mut self, now_ms: u64) -> Heartbeat {
        self.heartbeat_seq += 1;
        Heartbeat {
            seq: self.heartbeat_seq,
            state: self.state,
            at_ms: now_ms,
            uptime_ms: now_ms.saturating_sub(self.start_ms),
            temperature_c: self.signal.last_value(),
            rolling_counter: self.last_rolling_counter,
            signal_age_ms: self.signal.signal_age_ms(now_ms),
            active_faults: self.signal.active_faults(),
            active_mitigations: self.mitigations.clone(),
            counters: self.signal.counters().clone(),
        }
    }

    /// Reacts to the signal becoming untrusted or trusted again.
    fn sync_with_signal(&mut self, step: &mut Step) {
        use GuardianState::*;
        if self.signal.is_disarmed() {
            // Stale or stuck signal. In CLEAR/MONITORING/WARNING we can no
            // longer judge the battery, so say so: DEGRADED + fallback warning.
            // In CRITICAL/MITIGATING nothing changes on purpose (latched): a
            // running mitigation is not withdrawn just because data is missing.
            if matches!(self.state, Clear | Monitoring | Warning) {
                let reason = format!("signal untrusted: {:?}", self.signal.disarming_faults());
                self.critical_since_ms = None;
                self.transition(Degraded, &reason, step);
                self.request(
                    MitigationAction::MonitoringUnavailableWarning,
                    &reason,
                    step,
                );
            }
        } else if matches!(self.state, Clear | Degraded) && self.signal.is_trusted() {
            // Enough valid samples in a row: start (CLEAR) or resume (DEGRADED)
            // monitoring. Leaving DEGRADED also lifts the fallback warning.
            let reason = format!(
                "{} consecutive valid samples",
                self.cfg.signal.trust_samples
            );
            self.release_all("signal trusted again", step);
            self.transition(Monitoring, &reason, step);
        }
    }

    /// Thermal state machine, run for every accepted sample.
    fn evaluate_thermal(&mut self, temp: f64, step: &mut Step) {
        use GuardianState::*;
        let t = self.cfg.thermal.clone();
        let rate = self.trend.rate_c_per_s();

        // MONITORING -> WARNING: too hot, or heating up too fast. The rate
        // check is the "early" in early warning: it can fire long before the
        // absolute threshold is reached.
        if self.state == Monitoring {
            if temp >= t.warning_c {
                let reason = format!("temperature {temp:.1} C >= {} C", t.warning_c);
                self.transition(Warning, &reason, step);
            } else if rate >= t.warning_rate_c_per_s {
                let reason = format!("rise rate {rate:.2} C/s >= {} C/s", t.warning_rate_c_per_s);
                self.transition(Warning, &reason, step);
            }
        }

        // Not `else`: a sample that just caused WARNING is evaluated as WARNING too.
        match self.state {
            Warning => {
                if temp >= t.critical_c {
                    // Above critical: start (or continue) the persistence timer.
                    // A single hot sample is not enough, it has to last.
                    let since = *self.critical_since_ms.get_or_insert(step.now_ms);
                    let held_ms = step.now_ms.saturating_sub(since);
                    if held_ms >= t.critical_persist_ms {
                        let reason = format!(
                            "temperature {temp:.1} C >= {} C for {held_ms} ms",
                            t.critical_c
                        );
                        self.enter_critical(&reason, step);
                    }
                } else {
                    // Below critical again: the persistence timer restarts.
                    self.critical_since_ms = None;
                    // WARNING -> MONITORING only with margin (hysteresis) and
                    // when it is no longer heating up fast.
                    if temp < t.warning_c - t.hysteresis_c && rate < t.warning_rate_c_per_s {
                        let reason = format!("temperature {temp:.1} C, rate {rate:.2} C/s");
                        self.transition(Monitoring, &reason, step);
                    }
                }
            }
            Mitigating => {
                if temp < t.critical_c - t.hysteresis_c {
                    // Improving: has to stay improved for recovery_hold_ms
                    // before the mitigation is lifted.
                    let since = *self.improved_since_ms.get_or_insert(step.now_ms);
                    if step.now_ms.saturating_sub(since) >= t.recovery_hold_ms {
                        let reason = format!("condition improved: temperature {temp:.1} C");
                        self.release_all(&reason, step);
                        self.transition(Monitoring, &reason, step);
                    }
                } else {
                    // Hot again: the recovery timer restarts.
                    self.improved_since_ms = None;
                }
                self.check_mitigation_timeout(step);
            }
            // CLEAR / DEGRADED are handled by sync_with_signal; CRITICAL is
            // never a resting state (enter_critical moves on to MITIGATING).
            _ => {}
        }
    }

    /// Mitigation failed if the condition did not start improving in time.
    /// Evaluated on samples and ticks, so it also fires when the signal is lost.
    fn check_mitigation_timeout(&mut self, step: &mut Step) {
        // Only relevant while mitigating and not (yet) improving.
        if self.state != GuardianState::Mitigating || self.improved_since_ms.is_some() {
            return;
        }
        let Some(since) = self.mitigation_since_ms else {
            return;
        };
        let elapsed = step.now_ms.saturating_sub(since);
        if elapsed >= self.cfg.thermal.mitigation_timeout_ms {
            // MITIGATING -> CRITICAL -> (next level) MITIGATING.
            let reason = format!("mitigation failed: no improvement within {elapsed} ms");
            self.enter_critical(&reason, step);
        }
    }

    /// CRITICAL -> request next mitigation level -> MITIGATING.
    // Both transitions happen in the same step, so CRITICAL is visible as a
    // state event but never stays. Called on the first CRITICAL (level 1) and
    // after every failed mitigation (level 2, re-requested on each timeout).
    fn enter_critical(&mut self, reason: &str, step: &mut Step) {
        self.transition(GuardianState::Critical, reason, step);
        self.critical_since_ms = None;
        self.improved_since_ms = None;
        // Escalate one level, but never beyond level 2.
        self.mitigation_level = (self.mitigation_level + 1).min(2);
        let action = match self.mitigation_level {
            1 => MitigationAction::ReducePowerMaxCooling,
            _ => MitigationAction::OccupantEvacuationWarning,
        };
        self.request(action, reason, step);
        // Restart the mitigation timeout.
        self.mitigation_since_ms = Some(step.now_ms);
        self.transition(
            GuardianState::Mitigating,
            &format!("mitigation requested: {action:?}"),
            step,
        );
    }

    /// Changes the state and records a state event (no-op if already there).
    fn transition(&mut self, to: GuardianState, reason: &str, step: &mut Step) {
        if self.state == to {
            return;
        }
        info!(from = ?self.state, ?to, reason, "state transition");
        step.events.push(GuardianEvent::State(StateEvent {
            seq: 0, // numbered in finish()
            from: self.state,
            to,
            reason: reason.to_string(),
            at_ms: step.now_ms,
            trigger: step.trigger.cloned(),
        }));
        self.state = to;
    }

    /// Requests a mitigation; re-requesting an active one re-asserts it.
    fn request(&mut self, action: MitigationAction, reason: &str, step: &mut Step) {
        if !self.mitigations.contains(&action) {
            self.mitigations.push(action);
        }
        let event = self.mitigation_event(action, MitigationStatus::Requested, reason, step);
        step.events.push(event);
    }

    /// Lifts every active mitigation (one RELEASED event each) and resets the
    /// escalation, so the next CRITICAL starts again at level 1.
    fn release_all(&mut self, reason: &str, step: &mut Step) {
        // mem::take empties the list and gives us the old content.
        for action in std::mem::take(&mut self.mitigations) {
            let event = self.mitigation_event(action, MitigationStatus::Released, reason, step);
            step.events.push(event);
        }
        self.mitigation_level = 0;
        self.mitigation_since_ms = None;
        self.improved_since_ms = None;
    }

    fn mitigation_event(
        &self,
        action: MitigationAction,
        status: MitigationStatus,
        reason: &str,
        step: &Step,
    ) -> GuardianEvent {
        info!(?action, ?status, reason, "mitigation");
        GuardianEvent::Mitigation(MitigationEvent {
            seq: 0, // numbered in finish()
            action,
            status,
            reason: reason.to_string(),
            at_ms: step.now_ms,
            trigger: step.trigger.cloned(),
        })
    }

    /// Fault events go first; they carry the state reached in this step.
    /// Every event gets the next number of the Guardian-wide event sequence.
    // Last part of every step: signal.rs reported fault *changes*; here they
    // become FaultEvents (with code, class, current state and trigger),
    // followed by the state/mitigation events collected in `step`.
    fn finish(&mut self, changes: Vec<FaultChange>, step: Step) -> Vec<GuardianEvent> {
        let mut events: Vec<GuardianEvent> = changes
            .into_iter()
            .map(|c| {
                info!(fault = ?c.kind, status = ?c.status, detail = %c.detail, "fault");
                GuardianEvent::Fault(FaultEvent {
                    seq: 0,
                    fault: c.kind,
                    catalog_id: c.kind.catalog_id().map(str::to_string),
                    class: c.kind.class(),
                    status: c.status,
                    detail: c.detail,
                    state: self.state,
                    at_ms: step.now_ms,
                    trigger: step.trigger.cloned(),
                })
            })
            .collect();
        events.extend(step.events);
        GuardianEvent::number(&mut events, &mut self.event_seq);
        events
    }
}
