/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! Battery Thermal Guardian: EV thermal-runaway early warning service.
//!
//! # Where the Guardian sits
//!
//! ```text
//! AZ3166 --MQTT--> Mosquitto --MQTT--> vss-uprotocol-publisher --uProtocol/Zenoh--> Guardian
//!                                                                                      |
//!                       heartbeat / state / fault / mitigation events  <--uProtocol----+
//! ```
//!
//! The Guardian only ever sees uProtocol messages. It does not know about MQTT,
//! CAN or the KUKSA Data Broker (architecture rule of the challenge).
//!
//! # Life of one temperature sample inside the Guardian
//!
//! 1. `main.rs` loads the config, opens a Zenoh-backed uProtocol transport
//!    ([`transport`]) and starts the service loop ([`service::run`]).
//! 2. [`service`] registers a listener on the input topic. When a uMessage
//!    arrives, the listener puts it into a queue. The service loop takes it out,
//!    decodes the JSON payload into a [`contract::VssSample`] and calls
//!    [`guardian::Guardian::on_sample`] with the current time.
//! 3. [`guardian`] is the decision core. It first asks [`signal`] whether the
//!    sample can be trusted. That check covers duplicates, ordering, delay,
//!    range and spikes, and the monitor also tracks stale and stuck signals.
//!    The answer is "accepted" or "rejected", plus a list of faults that were
//!    raised or cleared.
//! 4. Still in [`guardian`]: if the signal as a whole became untrusted, the
//!    state machine goes to DEGRADED. If the sample was accepted, the
//!    temperature and its rise rate (from [`thermal`]) drive the thermal state
//!    machine: MONITORING -> WARNING -> CRITICAL -> MITIGATING -> ...
//! 5. Everything that happened in that step comes back to [`service`] as a list
//!    of [`contract::GuardianEvent`]s (fault, state change, mitigation). The
//!    service publishes each one on its own uProtocol topic.
//!
//! Next to the samples, two timers drive the loop in [`service`]:
//! - a **tick** every 100 ms calls [`guardian::Guardian::on_tick`]. That is how
//!   a *missing* signal is noticed (TempSourceConnectionLost), and how a
//!   mitigation timeout can still fire when no samples arrive;
//! - a **heartbeat** every second publishes [`contract::Heartbeat`], a snapshot
//!   of state, last temperature, active faults and counters.
//!
//! # Modules
//!
//! - [`contract`]: payloads and topic IDs shared with other components (start here)
//! - [`config`]: all thresholds and timings, loaded from TOML
//! - [`service`]: uProtocol binding (subscribe VSS, publish events), the only async part
//! - [`guardian`]: deterministic decision core and state machine (no I/O, no clock)
//! - [`signal`]: signal integrity checks and fault lifecycle
//! - [`thermal`]: temperature rise rate over a sliding window
//! - [`transport`]: Zenoh transport and logging setup shared by the binaries

pub mod config;
pub mod contract;
pub mod guardian;
pub mod service;
pub mod signal;
pub mod thermal;
pub mod transport;
