/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! Entry point of the `guardian` binary (flow step 1 in `lib.rs`).
//!
//! Only wiring happens here: read the configuration, open the Zenoh transport,
//! hand both to `service::run` and wait until the process is asked to stop.

use std::path::PathBuf;

use clap::Parser;
use guardian::config::GuardianConfig;
use guardian::{service, transport};

/// Battery Thermal Guardian service (uProtocol over Zenoh).
// Command line arguments, parsed by clap from the field definitions below.
#[derive(Parser)]
struct Args {
    /// Guardian configuration (TOML). Built-in defaults are used if omitted.
    #[arg(short, long)]
    config: Option<PathBuf>,
    /// Zenoh configuration (JSON5), overrides `uprotocol.zenoh_config`.
    #[arg(long)]
    zenoh_config: Option<String>,
    /// DFM fault catalog (JSON), overrides `dfm.catalog`; enables DFM reporting.
    #[arg(long)]
    dfm_catalog: Option<PathBuf>,
}

// `#[tokio::main]` starts the async runtime and runs `main` inside it.
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    transport::init_logging();
    let args = Args::parse();

    // Configuration: the TOML file if given, otherwise the built-in defaults
    // from config.rs. A command line flag wins over the file.
    let mut cfg = match &args.config {
        Some(path) => GuardianConfig::load(path)?,
        None => GuardianConfig::default(),
    };
    if args.zenoh_config.is_some() {
        cfg.uprotocol.zenoh_config = args.zenoh_config;
    }
    if args.dfm_catalog.is_some() {
        cfg.dfm.catalog = args.dfm_catalog;
    }

    // Open the uProtocol transport (Zenoh underneath) under our authority name.
    let up = &cfg.uprotocol;
    let transport = transport::zenoh_transport(&up.authority, up.zenoh_config.as_deref()).await?;

    // Run the service until shutdown_signal() completes (Ctrl-C / SIGTERM).
    // All the real work happens in service.rs.
    service::run(transport, cfg, shutdown_signal()).await?;
    Ok(())
}

/// Ctrl-C or SIGTERM (sent by Podman / Ankaios when a workload is stopped).
// Completes as soon as either signal arrives; service::run then leaves its loop.
async fn shutdown_signal() {
    let mut term = tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
        .expect("cannot install SIGTERM handler");
    tokio::select! {
        _ = tokio::signal::ctrl_c() => {}
        _ = term.recv() => {}
    }
}
