/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! uProtocol binding of the Guardian core (flow steps 2 and 5 in `lib.rs`).
//!
//! Subscribes to the VSS input topic, feeds samples and supervision ticks into
//! the core and publishes heartbeat, state, fault and mitigation events. The
//! transport is injected, so the same code runs over Zenoh in production and
//! over an in-process transport in tests.
//!
//! Together with dfm.rs, this is the only code in the Guardian that does I/O
//! or reads the clock. Its job is to translate: uMessage in -> `Guardian`
//! method call -> `GuardianEvent`s out -> uMessages (and DFM records for
//! catalog faults). All decisions live in guardian.rs.

use std::future::Future;
use std::str::FromStr;
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use async_trait::async_trait;
use tokio::sync::mpsc;
use tracing::{debug, info, warn};
use up_rust::{
    LocalUriProvider, StaticUriProvider, UCode, UListener, UMessage, UMessageBuilder,
    UPayloadFormat, UStatus, UTransport, UUri,
};

use crate::config::GuardianConfig;
use crate::contract::{resource, GuardianEvent, VssSample};
use crate::dfm::DfmReporter;
use crate::guardian::Guardian;

/// How many received messages may wait for the service loop. Samples arrive
/// a few times per second, so this only fills up if the loop is stuck.
const INPUT_QUEUE_LEN: usize = 1024;

/// Wall-clock time in ms since UNIX epoch, the same time base as the
/// creation time in a uProtocol message id.
// Wall clock (not a monotonic clock) because it is compared with the time the
// publisher created the uMessage, which is also wall-clock time.
pub fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// Forwards received messages to the Guardian task without blocking the transport.
// The transport calls `on_receive` on its own threads. Instead of processing
// there, we only push the message into a queue; the service loop below owns
// the Guardian and processes messages one at a time, in arrival order. That
// way the Guardian never needs locks.
struct InputListener {
    tx: mpsc::Sender<UMessage>,
}

#[async_trait]
impl UListener for InputListener {
    async fn on_receive(&self, msg: UMessage) {
        // try_send never waits: if the queue is full the message is dropped
        // (and later shows up as a counter gap / stale signal in the Guardian).
        if self.tx.try_send(msg).is_err() {
            warn!("input queue full, message dropped");
        }
    }
}

/// Runs the Guardian until `shutdown` completes.
///
/// `transport` is any uProtocol transport: Zenoh in `main.rs`, the in-process
/// `LocalTransport` in tests.
pub async fn run(
    transport: Arc<dyn UTransport>,
    cfg: GuardianConfig,
    shutdown: impl Future<Output = ()>,
) -> Result<(), UStatus> {
    let up = &cfg.uprotocol;

    // Our own address: //<authority>/<entity_id>/<version>/<resource>. The
    // provider builds the topic uUri for each output resource (heartbeat,
    // state, fault, mitigation) in publish().
    let uri = StaticUriProvider::new(up.authority.clone(), up.entity_id, up.entity_version);

    // The topic we listen to, e.g. "//*/8001/1/8001": any authority, entity
    // 0x8001 (the VSS publisher), version 1, resource 0x8001 (temperature topic).
    let input_filter = UUri::from_str(&up.input_topic).map_err(|e| {
        UStatus::fail_with_code(UCode::INVALID_ARGUMENT, format!("input_topic: {e}"))
    })?;

    // DFM reporting runs on its own thread; None if no catalog is configured.
    let dfm = DfmReporter::start(&cfg.dfm)
        .map_err(|e| UStatus::fail_with_code(UCode::INVALID_ARGUMENT, e))?;

    // Subscribe: from now on every matching uMessage ends up in `rx`.
    let (tx, mut rx) = mpsc::channel(INPUT_QUEUE_LEN);
    let listener: Arc<dyn UListener> = Arc::new(InputListener { tx });
    transport
        .register_listener(&input_filter, None, listener.clone())
        .await?;
    info!(
        input = %input_filter.to_uri(false),
        guardian = %uri.get_source_uri().to_uri(false),
        "Battery Thermal Guardian started"
    );

    // Two timers next to the input queue:
    // - tick (100 ms): lets the Guardian notice things that happen when *no*
    //   message arrives (stale signal, mitigation timeout);
    // - heartbeat (1 s): periodic status message.
    let mut tick = tokio::time::interval(Duration::from_millis(up.tick_period_ms));
    let mut heartbeat = tokio::time::interval(Duration::from_millis(up.heartbeat_period_ms));

    // The decision core. Start time = now, so "no data since start" can be detected.
    let mut guardian = Guardian::new(cfg.clone(), now_ms());
    tokio::pin!(shutdown);

    // Main loop: wait for whichever comes first (message, tick, heartbeat,
    // shutdown), let the Guardian react, publish what it returns.
    loop {
        let events = tokio::select! {
            // A uMessage arrived on the input topic.
            Some(msg) = rx.recv() => {
                let now = now_ms();
                // uProtocol message ID (UUIDv7); copied into the events this
                // sample triggers, so evidence can point at the exact message.
                let message_id = msg.id().map(|id| id.to_hyphenated_string());
                match decode_sample(&msg) {
                    Ok((sample, sent_ms)) => {
                        debug!(?sample, sent_ms, "sample received");
                        guardian.on_sample(&sample, sent_ms, message_id, now)
                    }
                    // Not a usable sample: still report it (PayloadInvalid).
                    Err(e) => {
                        let id = message_id.unwrap_or_default();
                        guardian.on_invalid_payload(format!("message {id}: {e}"), now)
                    }
                }
            }
            // Supervision tick: time passed, maybe without any sample.
            _ = tick.tick() => guardian.on_tick(now_ms()),
            // Heartbeat: publish a status snapshot. It is not an event list,
            // so publish directly and skip the event loop below.
            _ = heartbeat.tick() => {
                let hb = guardian.heartbeat(now_ms());
                publish(&*transport, &uri, resource::HEARTBEAT, serde_json::to_vec(&hb)).await;
                continue;
            }
            // Ctrl-C / SIGTERM: leave the loop.
            _ = &mut shutdown => break,
        };

        // Publish every event the Guardian produced in this step, in order.
        // Each event type has its own topic (state 0x8002, fault 0x8003,
        // mitigation 0x8004). Catalog faults also go to the DFM.
        for event in events {
            if let (Some(dfm), GuardianEvent::Fault(fault)) = (&dfm, &event) {
                dfm.report(fault);
            }
            publish(&*transport, &uri, event.resource_id(), event.to_json()).await;
        }
    }

    // Clean shutdown: stop receiving messages.
    info!("Battery Thermal Guardian stopping");
    transport
        .unregister_listener(&input_filter, None, listener)
        .await
}

/// uMessage -> (`VssSample`, send time in ms since epoch).
///
/// The sample comes from the JSON payload (format in contract.rs). The send
/// time is the creation time of the uMessage, which uProtocol stores in its
/// UUIDv7 message id.
fn decode_sample(msg: &UMessage) -> Result<(VssSample, u64), String> {
    let sent_ms = msg
        .id()
        .and_then(|id| id.get_time())
        .ok_or("no uProtocol (UUIDv7) message id")?;
    let payload = msg.payload.as_ref().ok_or("empty payload")?;
    let sample = serde_json::from_slice(payload).map_err(|e| e.to_string())?;
    Ok((sample, sent_ms))
}

/// Wraps a JSON payload into a uProtocol PUBLISH message on
/// `//<authority>/<entity>/<version>/<resource_id>` and sends it.
/// Errors are logged, not returned: a failed publish must not stop the Guardian.
async fn publish(
    transport: &dyn UTransport,
    uri: &StaticUriProvider,
    resource_id: u16,
    payload: serde_json::Result<Vec<u8>>,
) {
    let payload = match payload {
        Ok(p) => p,
        Err(e) => return warn!("cannot serialize event: {e}"),
    };
    // The builder fills in the uProtocol attributes: message type PUBLISH,
    // a fresh message ID, source = our topic uUri, payload format JSON.
    let msg = match UMessageBuilder::publish(uri.get_resource_uri(resource_id))
        .build_with_payload(payload, UPayloadFormat::UPAYLOAD_FORMAT_JSON)
    {
        Ok(m) => m,
        Err(e) => return warn!("cannot build message: {e}"),
    };
    if let Err(e) = transport.send(msg).await {
        warn!(resource_id, "publish failed: {e}");
    }
}
