/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! Signal integrity monitor: decides per sample whether the temperature value
//! can be trusted and tracks the lifecycle (raised / cleared) of signal and
//! transport faults.
//!
//! Rejected samples never refresh signal freshness, so a persistently faulty
//! stream (delayed, out of range, spiking, ...) ends up as
//! TempSourceConnectionLost instead of silently keeping the Guardian in
//! MONITORING.
//!
//! Called by guardian.rs (flow step 3 in `lib.rs`). Like the Guardian core it
//! has no clock: the current time is always passed in.
//!
//! # Checks per sample, in this order (first failing check wins)
//!
//! | check         | fault                                      | compares                               |
//! |---------------|--------------------------------------------|----------------------------------------|
//! | `check_order` | TransportDuplicate / TransportOutOfOrder   | seq and send time vs previous sample   |
//! | latency       | TransportDelay                             | arrival time - uMessage creation time  |
//! | range         | TempOutOfRange                             | value with [min_c, max_c]              |
//! | `check_spike` | TempSignalSpike                            | rate of change vs last accepted value  |
//!
//! A sample that passes all of them is *accepted*. Two more faults are not
//! about a single sample but about the stream: TempSignalStuck (value does
//! not change, checked on accepted samples) and TempSourceConnectionLost (no
//! accepted sample for a while, checked on the tick).
//!
//! # Fault lifecycle
//!
//! A fault is reported once when it appears (Raised). If it happens again
//! while active, it is not reported again. Per-sample faults clear after
//! `heal_samples` accepted samples in a row. TempSourceConnectionLost clears
//! with the next accepted sample, TempSignalStuck when the value changes again.

use std::collections::BTreeMap;

use crate::config::SignalConfig;
use crate::contract::{Counters, FaultKind, FaultStatus, VssSample};

/// Result of checking one sample.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Verdict {
    Accepted,
    /// Discarded; the fault says why.
    Rejected(FaultKind),
}

/// A fault that appeared or disappeared while processing one input. The
/// Guardian turns each of these into a FaultEvent.
#[derive(Debug, Clone, PartialEq)]
pub struct FaultChange {
    pub kind: FaultKind,
    pub status: FaultStatus,
    pub detail: String,
}

/// A temperature value with its send time (uMessage creation).
#[derive(Debug, Clone, Copy)]
struct Point {
    value: f64,
    sent_ms: u64,
}

/// A fast jump that was rejected as a possible spike, kept to see whether
/// the following samples confirm it.
#[derive(Debug, Clone, Copy)]
struct PendingJump {
    point: Point,
    confirmations: u32,
}

/// The value the signal currently "sits on" and since when.
#[derive(Debug, Clone, Copy)]
struct StuckTracker {
    value: f64,
    since_ms: u64,
}

pub struct SignalMonitor {
    cfg: SignalConfig,
    /// Guardian start time; reference for "no sample since start".
    start_ms: u64,
    /// seq and send time of the last sample that passed the order check
    /// (even if a later check rejected it).
    last_seq: Option<u64>,
    last_sent_ms: Option<u64>,
    /// Last sample that passed *all* checks: the value we currently trust.
    last_accepted: Option<Point>,
    /// Guardian time when `last_accepted` arrived (for staleness).
    last_accepted_rx_ms: Option<u64>,
    pending_jump: Option<PendingJump>,
    stuck: Option<StuckTracker>,
    /// Accepted samples in a row; trust needs `trust_samples` of them.
    valid_streak: u32,
    /// Active faults with their count of consecutive accepted samples since last occurrence.
    // BTreeMap keeps the faults sorted, so heartbeats list them in a stable order.
    active: BTreeMap<FaultKind, u32>,
    counters: Counters,
}

impl SignalMonitor {
    pub fn new(cfg: SignalConfig, start_ms: u64) -> Self {
        Self {
            cfg,
            start_ms,
            last_seq: None,
            last_sent_ms: None,
            last_accepted: None,
            last_accepted_rx_ms: None,
            pending_jump: None,
            stuck: None,
            valid_streak: 0,
            active: BTreeMap::new(),
            counters: Counters::default(),
        }
    }

    /// A fault is active that makes the whole signal untrusted.
    // i.e. STALE or STUCK is active (see FaultKind::disarms_signal).
    pub fn is_disarmed(&self) -> bool {
        self.active.keys().any(|k| k.disarms_signal())
    }

    /// Signal is trusted: not disarmed and enough consecutive valid samples.
    // Used by the Guardian to leave CLEAR or DEGRADED.
    pub fn is_trusted(&self) -> bool {
        !self.is_disarmed() && self.valid_streak >= self.cfg.trust_samples
    }

    pub fn active_faults(&self) -> Vec<FaultKind> {
        self.active.keys().copied().collect()
    }

    pub fn disarming_faults(&self) -> Vec<FaultKind> {
        self.active
            .keys()
            .copied()
            .filter(|k| k.disarms_signal())
            .collect()
    }

    pub fn last_value(&self) -> Option<f64> {
        self.last_accepted.map(|p| p.value)
    }

    pub fn signal_age_ms(&self, now_ms: u64) -> Option<u64> {
        self.last_accepted_rx_ms.map(|rx| now_ms.saturating_sub(rx))
    }

    pub fn counters(&self) -> &Counters {
        &self.counters
    }

    /// Runs all per-sample checks (see the table at the top of this file).
    /// `sent_ms` is when the publisher created the uMessage (from its id).
    pub fn on_sample(
        &mut self,
        s: &VssSample,
        sent_ms: u64,
        now_ms: u64,
    ) -> (Verdict, Vec<FaultChange>) {
        let mut changes = Vec::new();
        self.counters.received += 1;

        // 1. Order: duplicate or older than what we already have?
        if let Some((kind, detail)) = self.check_order(s, sent_ms) {
            return self.reject(kind, detail, changes);
        }
        // From here on this sample is "the newest one" for the order check.
        self.last_seq = Some(s.seq);
        self.last_sent_ms = Some(sent_ms);

        // 2. Latency: how long between the publisher creating the message and
        //    its arrival here? Needs both clocks to agree (same host or NTP).
        let latency_ms = now_ms.saturating_sub(sent_ms);
        if latency_ms > self.cfg.max_latency_ms {
            let detail = format!(
                "latency {latency_ms} ms exceeds {} ms",
                self.cfg.max_latency_ms
            );
            return self.reject(FaultKind::TransportDelay, detail, changes);
        }

        // 3. Range: physically plausible value? (NaN/infinity also fail here.)
        if !s.value.is_finite() || s.value < self.cfg.min_c || s.value > self.cfg.max_c {
            let detail = format!(
                "value {} outside plausible range [{}, {}]",
                s.value, self.cfg.min_c, self.cfg.max_c
            );
            return self.reject(FaultKind::TempOutOfRange, detail, changes);
        }

        // 4. Spike: implausibly fast change compared to the last trusted value?
        let point = Point {
            value: s.value,
            sent_ms,
        };
        if let Some(detail) = self.check_spike(point) {
            return self.reject(FaultKind::TempSignalSpike, detail, changes);
        }

        // Sample accepted.
        self.counters.accepted += 1;
        self.valid_streak = self.valid_streak.saturating_add(1);
        self.last_accepted = Some(point);
        // Freshness is only refreshed here, by accepted samples.
        self.last_accepted_rx_ms = Some(now_ms);

        // Data is flowing again -> STALE is over.
        if self
            .active
            .contains_key(&FaultKind::TempSourceConnectionLost)
        {
            self.clear(
                FaultKind::TempSourceConnectionLost,
                "accepted sample received".into(),
                &mut changes,
            );
        }
        // Stream-level check that needs accepted values: is the value frozen?
        self.update_stuck(point, &mut changes);
        // One more good sample for every active per-sample fault.
        self.heal_sample_faults(&mut changes);

        (Verdict::Accepted, changes)
    }

    /// Payload that could not be decoded as a VSS sample.
    pub fn on_invalid_payload(&mut self, detail: String) -> Vec<FaultChange> {
        self.counters.received += 1;
        // `.1` = only the fault changes; the verdict is not needed here.
        self.reject(FaultKind::PayloadInvalid, detail, Vec::new()).1
    }

    /// Time-driven supervision: detects a missing stream.
    pub fn on_tick(&mut self, now_ms: u64) -> Vec<FaultChange> {
        let mut changes = Vec::new();
        // Age of the last accepted sample; before the first one, time since start.
        let reference = self.last_accepted_rx_ms.unwrap_or(self.start_ms);
        let age = now_ms.saturating_sub(reference);
        if age >= self.cfg.stale_timeout_ms
            && !self
                .active
                .contains_key(&FaultKind::TempSourceConnectionLost)
        {
            let detail = match self.last_accepted_rx_ms {
                Some(_) => format!("no accepted sample for {age} ms"),
                None => format!("no accepted sample since start ({age} ms)"),
            };
            self.raise(FaultKind::TempSourceConnectionLost, detail, &mut changes);
            // Trust has to be re-earned once samples arrive again.
            self.valid_streak = 0;
            self.stuck = None;
            self.pending_jump = None;
        }
        changes
    }

    /// Duplicate / reordering check based on `seq` and the send time.
    /// Returns the fault if the sample must be rejected.
    fn check_order(&mut self, s: &VssSample, sent_ms: u64) -> Option<(FaultKind, String)> {
        // First sample ever: nothing to compare with.
        let (Some(last_seq), Some(last_sent)) = (self.last_seq, self.last_sent_ms) else {
            return None;
        };
        // Same seq again: re-delivery (or a device whose counter is frozen).
        if s.seq == last_seq {
            return Some((
                FaultKind::TransportDuplicate,
                format!("seq {} already received", s.seq),
            ));
        }
        // Lower seq and not newer: an old sample overtaken by a newer one.
        if s.seq < last_seq && sent_ms <= last_sent {
            return Some((
                FaultKind::TransportOutOfOrder,
                format!("seq {} received after seq {last_seq}", s.seq),
            ));
        }
        // Higher seq but time went backwards: also not trustworthy.
        if s.seq > last_seq && sent_ms < last_sent {
            return Some((
                FaultKind::TransportOutOfOrder,
                format!("sent at {sent_ms}, older than {last_sent}"),
            ));
        }
        // seq jumped (e.g. 5 -> 8): samples got lost on the way. Counted, not rejected.
        if s.seq > last_seq + 1 {
            self.counters.missing += s.seq - last_seq - 1;
        }
        // seq < last_seq but sent later: the publisher restarted its counter.
        None
    }

    /// Returns a detail text if the sample is an unconfirmed jump.
    // Example with spike_confirm_samples = 2 and last accepted 30 C:
    //   90 -> rejected, remembered as pending; next 30 -> normal, accepted
    //         => it was a spike.
    //   60 -> rejected, pending; next 60.2 agrees with 60 -> accepted
    //         => it was a real, fast rise. This matters because thermal
    //         runaway can rise very fast, and a filter must not hide it.
    fn check_spike(&mut self, point: Point) -> Option<String> {
        // Nothing accepted yet: no reference to compare with.
        let last = self.last_accepted?;
        let rate = rate_c_per_s(last, point);
        if rate <= self.cfg.max_rate_c_per_s {
            // Normal change: forget any pending jump.
            self.pending_jump = None;
            return None;
        }
        // A fast change is genuine if consecutive samples agree with each other.
        let confirmations = match self.pending_jump {
            Some(p) if rate_c_per_s(p.point, point) <= self.cfg.max_rate_c_per_s => {
                p.confirmations + 1
            }
            _ => 1,
        };
        if confirmations >= self.cfg.spike_confirm_samples {
            // Confirmed: accept it as the new level.
            self.pending_jump = None;
            return None;
        }
        // Not (yet) confirmed: reject, but remember it.
        self.pending_jump = Some(PendingJump {
            point,
            confirmations,
        });
        Some(format!(
            "rate {rate:.1} C/s exceeds {} C/s ({} -> {})",
            self.cfg.max_rate_c_per_s, last.value, point.value
        ))
    }

    /// Raises TempSignalStuck when the value stays the same for `stuck_window_ms`,
    /// clears it when the value moves again.
    fn update_stuck(&mut self, point: Point, changes: &mut Vec<FaultChange>) {
        if self.cfg.stuck_window_ms == 0 {
            return; // stuck detection disabled
        }
        match self.stuck {
            // Same value as before (within epsilon): how long already?
            Some(t) if (point.value - t.value).abs() <= self.cfg.stuck_epsilon_c => {
                let unchanged_ms = point.sent_ms.saturating_sub(t.since_ms);
                if unchanged_ms >= self.cfg.stuck_window_ms
                    && !self.active.contains_key(&FaultKind::TempSignalStuck)
                {
                    let detail = format!("value {} unchanged for {unchanged_ms} ms", t.value);
                    self.raise(FaultKind::TempSignalStuck, detail, changes);
                }
            }
            // First sample, or the value changed: start watching the new value.
            _ => {
                self.stuck = Some(StuckTracker {
                    value: point.value,
                    since_ms: point.sent_ms,
                });
                if self.active.contains_key(&FaultKind::TempSignalStuck) {
                    // Samples during the stuck phase do not count towards trust.
                    self.valid_streak = 1;
                    self.clear(
                        FaultKind::TempSignalStuck,
                        "value changes again".into(),
                        changes,
                    );
                }
            }
        }
    }

    /// After an accepted sample: count it for every active per-sample fault
    /// and clear those that have seen `heal_samples` good samples in a row.
    fn heal_sample_faults(&mut self, changes: &mut Vec<FaultChange>) {
        let heal_samples = self.cfg.heal_samples;
        let healed: Vec<FaultKind> = self
            .active
            .iter_mut()
            // STALE and STUCK have their own clearing rules (see above).
            .filter(|(kind, _)| !kind.disarms_signal())
            .filter_map(|(kind, clean)| {
                *clean += 1;
                (*clean >= heal_samples).then_some(*kind)
            })
            .collect();
        for kind in healed {
            let detail = format!("{heal_samples} consecutive valid samples");
            self.clear(kind, detail, changes);
        }
    }

    /// Common path for every rejected input: count it, break the trust
    /// streak, raise (or refresh) the fault.
    fn reject(
        &mut self,
        kind: FaultKind,
        detail: String,
        mut changes: Vec<FaultChange>,
    ) -> (Verdict, Vec<FaultChange>) {
        self.counters.rejected += 1;
        self.valid_streak = 0;
        self.raise(kind, detail, &mut changes);
        (Verdict::Rejected(kind), changes)
    }

    /// Marks a fault active. Reports it only if it was not active before.
    fn raise(&mut self, kind: FaultKind, detail: String, changes: &mut Vec<FaultChange>) {
        // Re-occurrence of an active fault restarts its healing, but is not reported again.
        // (insert returns the old value; None means the fault was not active.)
        if self.active.insert(kind, 0).is_none() {
            changes.push(FaultChange {
                kind,
                status: FaultStatus::Raised,
                detail,
            });
        }
    }

    /// Marks a fault inactive and reports it, if it was active.
    fn clear(&mut self, kind: FaultKind, detail: String, changes: &mut Vec<FaultChange>) {
        if self.active.remove(&kind).is_some() {
            changes.push(FaultChange {
                kind,
                status: FaultStatus::Cleared,
                detail,
            });
        }
    }
}

/// Absolute rate of change between two points in C/s.
// Time difference at least 1 ms, so equal send times do not divide by zero.
fn rate_c_per_s(from: Point, to: Point) -> f64 {
    let dt_ms = to.sent_ms.saturating_sub(from.sent_ms).max(1);
    (to.value - from.value).abs() * 1000.0 / dt_ms as f64
}
