/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! Temperature trend over a sliding window of accepted samples.
//!
//! Used by guardian.rs for the "trend exceeded" part of MONITORING -> WARNING:
//! a battery heating up quickly is a warning sign even below the threshold.
//! Only accepted samples are pushed here, so rejected spikes cannot fake a trend.

use std::collections::VecDeque;

/// The last `window_ms` worth of (time_ms, temperature) points.
pub struct Trend {
    window_ms: u64,
    // Oldest point at the front, newest at the back.
    points: VecDeque<(u64, f64)>,
}

impl Trend {
    pub fn new(window_ms: u64) -> Self {
        Self {
            window_ms,
            points: VecDeque::new(),
        }
    }

    /// Adds a point and drops points that are now older than the window.
    pub fn push(&mut self, time_ms: u64, value: f64) {
        self.points.push_back((time_ms, value));
        while let Some(&(t, _)) = self.points.front() {
            if time_ms.saturating_sub(t) > self.window_ms {
                self.points.pop_front();
            } else {
                break;
            }
        }
    }

    /// Forgets all points (called when the signal went stale).
    pub fn clear(&mut self) {
        self.points.clear();
    }

    /// Rise rate in C/s between oldest and newest point of the window.
    /// Returns 0 until the window is at least half filled, so start-up noise
    /// cannot trigger a rate warning.
    // Positive = heating up, negative = cooling down. Example: window 10 s,
    // 30.0 C ten seconds ago and 36.0 C now -> 0.6 C/s.
    pub fn rate_c_per_s(&self) -> f64 {
        let (Some(&(t0, v0)), Some(&(t1, v1))) = (self.points.front(), self.points.back()) else {
            return 0.0;
        };
        let span_ms = t1.saturating_sub(t0);
        if span_ms == 0 || span_ms < self.window_ms / 2 {
            return 0.0;
        }
        (v1 - v0) * 1000.0 / span_ms as f64
    }
}
