/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! Zenoh transport setup shared by all binaries.
//!
//! uProtocol defines *what* a message looks like (uMessage, uUri, ...), the
//! transport decides *how* it travels. `UPTransportZenoh` is the uProtocol
//! transport implementation on top of the Zenoh middleware. Everything above
//! this file only uses the generic `UTransport` trait, so Zenoh could be
//! swapped for another transport without touching the Guardian logic.

use std::sync::Arc;

use up_transport_zenoh::{zenoh_config, UPTransportZenoh};

/// Opens a uProtocol transport over Zenoh.
///
/// `authority` is the uProtocol name of this device (e.g. "vehicle"); it
/// becomes the first part of every uUri we publish (`//vehicle/...`).
/// Without a Zenoh config file Zenoh runs in peer mode and finds other
/// processes on the network by multicast scouting.
pub async fn zenoh_transport(
    authority: &str,
    zenoh_config_path: Option<&str>,
) -> Result<Arc<UPTransportZenoh>, Box<dyn std::error::Error + Send + Sync>> {
    let config = match zenoh_config_path {
        Some(path) => zenoh_config::Config::from_file(path)?,
        None => zenoh_config::Config::default(),
    };
    let transport = UPTransportZenoh::builder(authority)?
        .with_config(config)
        .build()
        .await?;
    // Arc: the transport is shared between the service loop and the listener.
    Ok(Arc::new(transport))
}

/// Logs go to stderr, so stdout stays free for machine-readable output.
// Log level comes from RUST_LOG (e.g. RUST_LOG=debug); default is info,
// with Zenoh's own logs reduced to warnings. Colors only on a real terminal,
// so log files and container logs stay plain text.
pub fn init_logging() {
    let filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info,zenoh=warn"));
    tracing_subscriber::fmt()
        .with_env_filter(filter)
        .with_writer(std::io::stderr)
        .with_ansi(std::io::IsTerminal::is_terminal(&std::io::stderr()))
        .init();
}
