/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! The Guardian's fault kinds must match the DFM fault catalog.
//!
//! The DFM only accepts faults whose id is in its catalog, so a typo on
//! either side would silently drop faults. This test fails if the catalog
//! and `FaultKind` drift apart.
//!
//! The catalog is read from dfm-container/ at compile time, i.e. the same
//! file the DFM container loads, so this test needs the full repository.

use guardian::contract::FaultKind;
use serde_json::Value;

const CATALOG: &str = include_str!("../../dfm-container/battery_guardian_catalog.json");

/// (id, name) of every fault in the catalog.
fn catalog_faults() -> Vec<(String, String)> {
    let catalog: Value = serde_json::from_str(CATALOG).unwrap();
    assert_eq!(catalog["id"], "battery");
    catalog["faults"]
        .as_array()
        .unwrap()
        .iter()
        .map(|f| {
            (
                f["id"]["Text"].as_str().unwrap().to_string(),
                f["name"].as_str().unwrap().to_string(),
            )
        })
        .collect()
}

/// Name of a fault kind as it appears in JSON (= catalog `name`).
fn json_name(kind: FaultKind) -> String {
    serde_json::to_value(kind)
        .unwrap()
        .as_str()
        .unwrap()
        .to_string()
}

// Every catalog fault exists in the Guardian with the same id and name.
#[test]
fn every_catalog_fault_is_known_to_the_guardian() {
    for (id, name) in catalog_faults() {
        let kind = FaultKind::ALL
            .into_iter()
            .find(|k| k.catalog_id() == Some(id.as_str()))
            .unwrap_or_else(|| panic!("catalog fault {id} has no FaultKind"));
        assert_eq!(json_name(kind), name, "name mismatch for {id}");
    }
}

// Every catalog id the Guardian uses exists in the catalog.
#[test]
fn every_guardian_catalog_id_is_in_the_catalog() {
    let ids: Vec<String> = catalog_faults().into_iter().map(|(id, _)| id).collect();
    for kind in FaultKind::ALL {
        if let Some(id) = kind.catalog_id() {
            assert!(ids.iter().any(|c| c == id), "{kind:?}: {id} not in catalog");
        }
    }
}

// Guardian-internal faults stay out of the DFM.
#[test]
fn transport_faults_are_not_in_the_catalog() {
    for kind in [
        FaultKind::TransportDelay,
        FaultKind::TransportDuplicate,
        FaultKind::TransportOutOfOrder,
        FaultKind::PayloadInvalid,
    ] {
        assert_eq!(kind.catalog_id(), None, "{kind:?}");
    }
}
