/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! Behaviour of the Guardian decision core, driven with explicit time.
//!
//! No transport and no real clock: the tests call `Guardian::on_sample` /
//! `on_tick` directly with a simulated time `now`. A test that "waits" 30 s
//! therefore runs in microseconds, and every run is identical.
//!
//! The `Harness` below plays the role of service.rs: it owns the Guardian,
//! advances the simulated clock, delivers samples and collects all events.

use guardian::config::GuardianConfig;
use guardian::contract::{
    FaultKind, FaultStatus, GuardianEvent, GuardianState, MitigationAction, MitigationStatus,
    VssSample, VSS_BATTERY_TEMPERATURE_MAX,
};
use guardian::guardian::Guardian;
use GuardianState::*;

/// Simulated start time (any epoch-ms value works).
const T0: u64 = 1_700_000_000_000;
/// Time between two samples, i.e. a 2 Hz signal.
const PERIOD_MS: u64 = 500;

/// Test driver: a Guardian plus simulated time and an event log.
struct Harness {
    guardian: Guardian,
    /// Simulated current time.
    now: u64,
    /// seq of the last sample sent by `sample()`.
    seq: u64,
    /// Every event the Guardian produced so far, in order.
    events: Vec<GuardianEvent>,
}

impl Harness {
    fn new() -> Self {
        Self::with(GuardianConfig::default())
    }

    fn with(cfg: GuardianConfig) -> Self {
        Self {
            guardian: Guardian::new(cfg, T0),
            now: T0,
            seq: 0,
            events: Vec::new(),
        }
    }

    /// Delivers one sample with full control over seq and send time, without
    /// advancing time. Used to craft duplicates, reordering and delays.
    // `sent_ms` stands in for the creation time in the uMessage id.
    fn sample_raw(&mut self, seq: u64, sent_ms: u64, value: f64) -> Vec<GuardianEvent> {
        let s = VssSample {
            path: VSS_BATTERY_TEMPERATURE_MAX.into(),
            value,
            seq,
            rolling_counter: Some(seq % 256),
            correlation_id: Some("run-1".into()),
        };
        // "msg-<seq>" stands in for the uProtocol message ID.
        let ev = self
            .guardian
            .on_sample(&s, sent_ms, Some(format!("msg-{seq}")), self.now);
        self.events.extend(ev.clone());
        ev
    }

    /// Advances one period, ticks, then delivers one fresh sample.
    // "Fresh" = next seq, sent now (no transport delay).
    fn sample(&mut self, value: f64) -> Vec<GuardianEvent> {
        self.advance(PERIOD_MS);
        self.seq += 1;
        self.sample_raw(self.seq, self.now, value)
    }

    /// Moves the clock forward and runs one supervision tick.
    fn advance(&mut self, ms: u64) {
        self.now += ms;
        let ev = self.guardian.on_tick(self.now);
        self.events.extend(ev);
    }

    /// Advances time in tick-sized steps without samples.
    // Simulates a dropout: only ticks, like service.rs does every 100 ms.
    fn silence(&mut self, ms: u64) {
        for _ in 0..ms / 100 {
            self.advance(100);
        }
    }

    /// Feeds samples moving from `from` towards `to` at `rate` C/s, with a
    /// +-0.1 C ripple so the signal never looks stuck.
    fn ramp(&mut self, from: f64, to: f64, rate_c_per_s: f64) {
        let step = rate_c_per_s * PERIOD_MS as f64 / 1000.0;
        let n = ((to - from).abs() / step).ceil() as usize;
        for i in 0..=n {
            let v = from + (to - from).signum() * (step * i as f64).min((to - from).abs());
            self.sample(v + ripple(self.seq));
        }
    }

    /// Feeds samples around `value` (with ripple) for `ms` milliseconds.
    fn hold(&mut self, value: f64, ms: u64) {
        for _ in 0..ms / PERIOD_MS {
            self.sample(value + ripple(self.seq));
        }
    }

    /// Brings the Guardian into MONITORING (3 valid samples) and forgets
    /// those start-up events, so a test only sees what it caused itself.
    fn monitoring(mut self) -> Self {
        self.hold(30.0, 3 * PERIOD_MS);
        assert_eq!(self.guardian.state(), Monitoring);
        self.events.clear();
        self
    }

    // Short views on the event log, easy to compare in assertions.

    /// Target states of all state events, in order.
    fn states(&self) -> Vec<GuardianState> {
        states(&self.events)
    }

    /// (fault, raised/cleared) of all fault events, in order.
    fn faults(&self) -> Vec<(FaultKind, FaultStatus)> {
        faults(&self.events)
    }

    /// (action, requested/released) of all mitigation events, in order.
    fn mitigations(&self) -> Vec<(MitigationAction, MitigationStatus)> {
        self.events
            .iter()
            .filter_map(|e| match e {
                GuardianEvent::Mitigation(m) => Some((m.action, m.status)),
                _ => None,
            })
            .collect()
    }
}

/// +0.1 / -0.1 alternating, so values are never exactly repeated.
fn ripple(seq: u64) -> f64 {
    match seq % 2 {
        0 => 0.1,
        _ => -0.1,
    }
}

fn states(events: &[GuardianEvent]) -> Vec<GuardianState> {
    events
        .iter()
        .filter_map(|e| match e {
            GuardianEvent::State(s) => Some(s.to),
            _ => None,
        })
        .collect()
}

fn faults(events: &[GuardianEvent]) -> Vec<(FaultKind, FaultStatus)> {
    events
        .iter()
        .filter_map(|e| match e {
            GuardianEvent::Fault(f) => Some((f.fault, f.status)),
            _ => None,
        })
        .collect()
}

/// True if `needle` appears in `haystack` in this order (gaps allowed).
fn contains_in_order<T: PartialEq + std::fmt::Debug>(haystack: &[T], needle: &[T]) -> bool {
    let mut it = haystack.iter();
    needle.iter().all(|n| it.any(|h| h == n))
}

// ---------------------------------------------------------------- baseline

// CLEAR -> MONITORING needs trust_samples (3) valid samples, not just one.
#[test]
fn starts_clear_and_monitors_once_signal_is_trusted() {
    let mut h = Harness::new();
    assert_eq!(h.guardian.state(), Clear);
    h.sample(30.0);
    h.sample(30.1);
    assert_eq!(h.guardian.state(), Clear);
    h.sample(30.0);
    assert_eq!(h.states(), vec![Monitoring]);
    assert!(h.faults().is_empty());
}

// A healthy signal for one minute produces no events at all (no false alarms).
#[test]
fn nominal_signal_stays_in_monitoring() {
    let mut h = Harness::new().monitoring();
    h.hold(30.0, 60_000);
    assert!(h.events.is_empty(), "unexpected events: {:?}", h.events);
}

// Other VSS signals on the same topic are not counted and cause nothing.
#[test]
fn samples_of_other_vss_paths_are_ignored() {
    let mut h = Harness::new();
    let s = VssSample {
        path: "Vehicle.Speed".into(),
        value: 500.0,
        seq: 1,
        rolling_counter: None,
        correlation_id: None,
    };
    assert!(h.guardian.on_sample(&s, T0, None, T0).is_empty());
    assert_eq!(h.guardian.heartbeat(T0).counters.received, 0);
}

// ---------------------------------------------------------------- thermal

// The full thermal path: heat up to 70 C (WARNING, then CRITICAL after 2 s
// above 65 C, mitigation requested), cool down (mitigation released, back to
// MONITORING). No signal faults on the way.
#[test]
fn overheat_runs_through_warning_critical_mitigation_and_recovers() {
    let mut h = Harness::new().monitoring();
    h.ramp(30.0, 70.0, 1.0);
    h.hold(70.0, 3000);
    assert_eq!(h.guardian.state(), Mitigating);
    assert_eq!(
        h.mitigations(),
        vec![(
            MitigationAction::ReducePowerMaxCooling,
            MitigationStatus::Requested
        )]
    );

    h.ramp(70.0, 30.0, 1.0);
    h.hold(30.0, 12_000);
    assert!(
        contains_in_order(&h.states(), &[Warning, Critical, Mitigating, Monitoring]),
        "{:?}",
        h.states()
    );
    assert_eq!(h.guardian.state(), Monitoring);
    assert_eq!(
        h.mitigations().last(),
        Some(&(
            MitigationAction::ReducePowerMaxCooling,
            MitigationStatus::Released
        ))
    );
    assert!(h.faults().is_empty(), "{:?}", h.faults());
}

// Heating at 1 C/s gives WARNING by trend while still far below 55 C.
#[test]
fn fast_rise_warns_before_the_temperature_threshold() {
    let mut h = Harness::new().monitoring();
    h.ramp(30.0, 45.0, 1.0);
    assert_eq!(h.guardian.state(), Warning);
    // The first state event is MONITORING -> WARNING; check why.
    let GuardianEvent::State(s) = &h
        .events
        .iter()
        .find(|e| matches!(e, GuardianEvent::State(_)))
        .unwrap()
    else {
        unreachable!()
    };
    assert!(s.reason.contains("rise rate"), "{}", s.reason);
}

// 66 C for only 0.5 s (shorter than critical_persist_ms) is not CRITICAL.
#[test]
fn short_excursion_above_critical_does_not_escalate() {
    let mut h = Harness::new().monitoring();
    h.ramp(30.0, 60.0, 2.0);
    h.sample(66.0);
    h.sample(66.0);
    h.ramp(60.0, 50.0, 2.0);
    assert!(!h.states().contains(&Critical), "{:?}", h.states());
}

// Temperature stays at 70 C: after mitigation_timeout_ms (30 s) the first
// mitigation counts as failed -> CRITICAL again -> level 2 requested.
#[test]
fn failed_mitigation_escalates_to_occupant_warning() {
    let mut h = Harness::new().monitoring();
    h.ramp(30.0, 70.0, 1.0);
    h.hold(70.0, 35_000);
    assert_eq!(h.guardian.state(), Mitigating);
    assert_eq!(
        h.mitigations(),
        vec![
            (
                MitigationAction::ReducePowerMaxCooling,
                MitigationStatus::Requested
            ),
            (
                MitigationAction::OccupantEvacuationWarning,
                MitigationStatus::Requested
            ),
        ]
    );
    let transitions = h.states();
    assert!(contains_in_order(
        &transitions,
        &[Critical, Mitigating, Critical, Mitigating]
    ));
}

// ---------------------------------------------------------------- source / signal faults

// No sample at all for stale_timeout_ms (3 s) after start: the Guardian must
// not sit silently in CLEAR -> STALE, DEGRADED, fallback warning.
#[test]
fn no_data_after_start_degrades_with_fallback_warning() {
    let mut h = Harness::new();
    h.silence(3000);
    assert_eq!(h.guardian.state(), Degraded);
    assert_eq!(
        h.faults(),
        vec![(FaultKind::TempSourceConnectionLost, FaultStatus::Raised)]
    );
    assert_eq!(
        h.mitigations(),
        vec![(
            MitigationAction::MonitoringUnavailableWarning,
            MitigationStatus::Requested
        )]
    );
}

// Signal drops out for 3 s, then comes back. STALE clears with the first
// sample, but MONITORING resumes only after 3 valid samples.
#[test]
fn dropout_degrades_and_recovers_after_trusted_samples() {
    let mut h = Harness::new().monitoring();
    h.silence(3000);
    assert_eq!(h.guardian.state(), Degraded);

    h.sample(30.0);
    assert_eq!(
        h.guardian.state(),
        Degraded,
        "one sample must not restore trust"
    );
    h.sample(30.1);
    h.sample(30.0);
    assert_eq!(h.guardian.state(), Monitoring);
    assert_eq!(
        h.faults(),
        vec![
            (FaultKind::TempSourceConnectionLost, FaultStatus::Raised),
            (FaultKind::TempSourceConnectionLost, FaultStatus::Cleared),
        ]
    );
    assert_eq!(
        h.mitigations(),
        vec![
            (
                MitigationAction::MonitoringUnavailableWarning,
                MitigationStatus::Requested
            ),
            (
                MitigationAction::MonitoringUnavailableWarning,
                MitigationStatus::Released
            ),
        ]
    );
}

// Exactly 31.5 C for 6 s (stuck window shortened to 5 s): STUCK -> DEGRADED.
// Once the value moves again, the fault clears and monitoring resumes.
#[test]
fn stuck_value_degrades_and_recovers_when_value_moves() {
    let mut cfg = GuardianConfig::default();
    cfg.signal.stuck_window_ms = 5000;
    let mut h = Harness::with(cfg).monitoring();
    for _ in 0..12 {
        h.sample(31.5);
    }
    assert_eq!(h.guardian.state(), Degraded);
    assert_eq!(
        h.faults(),
        vec![(FaultKind::TempSignalStuck, FaultStatus::Raised)]
    );

    h.hold(30.0, 3 * PERIOD_MS);
    assert_eq!(h.guardian.state(), Monitoring);
    assert_eq!(
        h.faults().last(),
        Some(&(FaultKind::TempSignalStuck, FaultStatus::Cleared))
    );
}

// One 200 C sample: rejected (last trusted value stays 30.1), fault raised,
// state unchanged; after heal_samples (5) good samples the fault clears.
#[test]
fn out_of_range_sample_is_rejected_without_state_change() {
    let mut h = Harness::new().monitoring();
    h.sample(200.0);
    assert_eq!(h.guardian.state(), Monitoring);
    assert_eq!(h.guardian.heartbeat(h.now).temperature_c, Some(30.1));
    h.hold(30.0, 5 * PERIOD_MS);
    assert_eq!(
        h.faults(),
        vec![
            (FaultKind::TempOutOfRange, FaultStatus::Raised),
            (FaultKind::TempOutOfRange, FaultStatus::Cleared),
        ]
    );
}

// Only 200 C samples: none is accepted, so freshness is never refreshed ->
// after 3 s STALE -> DEGRADED. Bad data must not keep the Guardian quiet.
#[test]
fn persistent_out_of_range_ends_in_degraded() {
    let mut h = Harness::new().monitoring();
    for _ in 0..8 {
        h.sample(200.0);
    }
    assert_eq!(h.guardian.state(), Degraded);
    assert!(h
        .faults()
        .contains(&(FaultKind::TempSourceConnectionLost, FaultStatus::Raised)));
}

// 30 -> 90 -> 30: the 90 is not confirmed by the next sample -> spike, ignored.
#[test]
fn single_spike_is_rejected() {
    let mut h = Harness::new().monitoring();
    h.sample(90.0);
    h.sample(30.0);
    assert_eq!(
        h.faults(),
        vec![(FaultKind::TempSignalSpike, FaultStatus::Raised)]
    );
    assert_eq!(h.guardian.state(), Monitoring);
    assert_eq!(h.guardian.heartbeat(h.now).temperature_c, Some(30.0));
}

// 30 -> 60 -> 60.2: the jump is confirmed by the next sample -> accepted as
// real (and 60 C >= warning_c gives WARNING).
#[test]
fn confirmed_fast_change_is_accepted() {
    let mut h = Harness::new().monitoring();
    h.sample(60.0);
    h.sample(60.2);
    assert_eq!(h.guardian.heartbeat(h.now).temperature_c, Some(60.2));
    assert_eq!(h.guardian.state(), Warning);
}

// ---------------------------------------------------------------- transport faults

// The last sample is delivered again (same seq): DUPLICATE, no state change.
#[test]
fn duplicate_is_rejected_and_heals() {
    let mut h = Harness::new().monitoring();
    let seq = h.seq;
    h.sample_raw(seq, h.now, 30.0);
    assert_eq!(
        h.faults(),
        vec![(FaultKind::TransportDuplicate, FaultStatus::Raised)]
    );
    h.hold(30.0, 5 * PERIOD_MS);
    assert_eq!(
        h.faults().last(),
        Some(&(FaultKind::TransportDuplicate, FaultStatus::Cleared))
    );
    assert!(h.states().is_empty());
}

// An older sample (lower seq, sent earlier) arrives after a newer one.
#[test]
fn out_of_order_sample_is_rejected() {
    let mut h = Harness::new().monitoring();
    let (seq, ts) = (h.seq, h.now);
    h.sample(30.0);
    h.sample_raw(seq - 1, ts - PERIOD_MS, 30.0);
    assert_eq!(
        h.faults(),
        vec![(FaultKind::TransportOutOfOrder, FaultStatus::Raised)]
    );
}

// seq starts again at 1 but the message was sent later: the publisher restarted.
#[test]
fn publisher_restart_is_not_out_of_order() {
    let mut h = Harness::new().monitoring();
    h.advance(PERIOD_MS);
    h.sample_raw(1, h.now, 30.0);
    assert!(h.faults().is_empty());
}

// A sample 1500 ms old on arrival (> max_latency_ms 1000): DELAY. Its seq
// also skips one number, which is counted as one missing sample.
#[test]
fn delayed_sample_is_rejected_and_counted_missing_on_gap() {
    let mut h = Harness::new().monitoring();
    // Sample produced 500 ms after the previous one, but delivered 1500 ms late.
    h.silence(2000);
    h.seq += 2;
    h.sample_raw(h.seq, h.now - 1500, 30.0);
    assert_eq!(
        h.faults(),
        vec![(FaultKind::TransportDelay, FaultStatus::Raised)]
    );
    let hb = h.guardian.heartbeat(h.now);
    assert_eq!(hb.counters.missing, 1);
    assert_eq!(hb.counters.rejected, 1);
}

// A message that is not a VssSample still leaves a trace.
#[test]
fn invalid_payload_is_reported() {
    let mut h = Harness::new();
    let ev = h.guardian.on_invalid_payload("expected value".into(), T0);
    assert_eq!(
        faults(&ev),
        vec![(FaultKind::PayloadInvalid, FaultStatus::Raised)]
    );
}

// ---------------------------------------------------------------- latching / evidence

// In MITIGATING the signal disappears for 31 s. Expected: STALE is reported,
// but the state stays MITIGATING (no DEGRADED), nothing is released, and the
// mitigation timeout still escalates to level 2.
#[test]
fn signal_loss_during_mitigation_keeps_mitigation_and_escalates() {
    let mut h = Harness::new().monitoring();
    h.ramp(30.0, 70.0, 1.0);
    h.hold(70.0, 3000);
    assert_eq!(h.guardian.state(), Mitigating);

    h.silence(31_000);
    assert_eq!(h.guardian.state(), Mitigating);
    assert!(h
        .faults()
        .contains(&(FaultKind::TempSourceConnectionLost, FaultStatus::Raised)));
    let m = h.mitigations();
    assert!(
        !m.iter().any(|(_, s)| *s == MitigationStatus::Released),
        "{m:?}"
    );
    assert_eq!(
        m.last(),
        Some(&(
            MitigationAction::OccupantEvacuationWarning,
            MitigationStatus::Requested
        ))
    );
}

// The CLEAR -> MONITORING event points at the 3rd sample: its seq, message ID
// and correlation ID (the evidence link).
#[test]
fn events_reference_triggering_sample() {
    let mut h = Harness::new();
    h.sample(30.0);
    h.sample(30.1);
    let ev = h.sample(30.0);
    let GuardianEvent::State(s) = &ev[0] else {
        panic!("expected state event, got {ev:?}");
    };
    let trigger = s.trigger.as_ref().unwrap();
    assert_eq!(trigger.seq, 3);
    assert_eq!(trigger.message_id.as_deref(), Some("msg-3"));
    assert_eq!(trigger.correlation_id.as_deref(), Some("run-1"));
}

// The STALE fault event already reports the state it led to (DEGRADED).
#[test]
fn fault_event_carries_resulting_state() {
    let mut h = Harness::new().monitoring();
    h.silence(3000);
    let fault = h
        .events
        .iter()
        .find_map(|e| match e {
            GuardianEvent::Fault(f) => Some(f),
            _ => None,
        })
        .unwrap();
    assert_eq!(fault.catalog_id.as_deref(), Some("btg.src.connection_lost"));
    assert_eq!(fault.state, Degraded);
}

// 3 good samples + one rejected: heartbeat shows the fault and the counters.
#[test]
fn heartbeat_reports_state_faults_and_counters() {
    let mut h = Harness::new().monitoring();
    h.sample(200.0);
    let hb = h.guardian.heartbeat(h.now);
    assert_eq!(hb.seq, 1);
    assert_eq!(hb.state, Monitoring);
    assert_eq!(hb.active_faults, vec![FaultKind::TempOutOfRange]);
    assert_eq!(hb.counters.received, 4);
    assert_eq!(hb.counters.accepted, 3);
    assert_eq!(hb.signal_age_ms, Some(PERIOD_MS));
    assert_eq!(h.guardian.heartbeat(h.now).seq, 2);
}

// Fault, state and mitigation events share one counter: 1, 2, 3, ... without gaps.
#[test]
fn events_are_numbered_consecutively_across_topics() {
    let mut h = Harness::new();
    h.silence(3000);
    h.hold(30.0, 3 * PERIOD_MS);
    let seqs: Vec<u64> = h.events.iter().map(GuardianEvent::seq).collect();
    assert_eq!(seqs, (1..=seqs.len() as u64).collect::<Vec<_>>());
    assert!(seqs.len() >= 6, "{:?}", h.events);
}

// rolling_counter and temperature_c in the heartbeat always come from the
// same (last accepted) sample.
#[test]
fn heartbeat_reports_rolling_counter_of_last_accepted_sample() {
    let mut h = Harness::new();
    assert_eq!(h.guardian.heartbeat(h.now).rolling_counter, None);
    h.hold(30.0, 3 * PERIOD_MS);
    assert_eq!(h.guardian.heartbeat(h.now).rolling_counter, Some(3));
    h.sample(200.0); // rejected: counter stays with the last accepted sample
    let hb = h.guardian.heartbeat(h.now);
    assert_eq!(
        (hb.rolling_counter, hb.temperature_c),
        (Some(3), Some(30.1))
    );
}

// Device keeps sending but its counter is frozen: every sample is a
// duplicate, nothing is accepted -> STALE -> DEGRADED.
#[test]
fn frozen_device_counter_ends_in_degraded() {
    // The publisher keeps the seq while the rolling counter does not move.
    let mut h = Harness::new().monitoring();
    let seq = h.seq;
    for _ in 0..8 {
        h.advance(PERIOD_MS);
        h.sample_raw(seq, h.now, 30.0);
    }
    assert_eq!(h.guardian.state(), Degraded);
    assert_eq!(
        h.faults(),
        vec![
            (FaultKind::TransportDuplicate, FaultStatus::Raised),
            (FaultKind::TempSourceConnectionLost, FaultStatus::Raised),
        ]
    );
}

// Determinism: the same input sequence twice gives exactly the same events.
// This is what makes fault campaigns replayable.
#[test]
fn identical_input_yields_identical_events() {
    let run = || {
        let mut h = Harness::new();
        h.hold(30.0, 2000);
        h.sample(200.0);
        h.ramp(30.0, 70.0, 1.0);
        h.silence(4000);
        h.hold(40.0, 6000);
        h.events
    };
    assert_eq!(run(), run());
}
