/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! The Guardian service end to end over a real uProtocol transport
//! (up-rust's in-process LocalTransport instead of Zenoh).
//!
//! Unlike guardian_core.rs this test goes through service.rs: real
//! uMessages in, real uMessages out, real (wall-clock) time. Setup:
//!
//! ```text
//! test --publish VssSample--> LocalTransport --> service::run (Guardian)
//!                                   |
//! Collector <--- all Guardian topics ---+
//! ```

use std::str::FromStr;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use async_trait::async_trait;
use guardian::config::GuardianConfig;
use guardian::contract::{
    resource, FaultEvent, Heartbeat, StateEvent, VssSample, VSS_BATTERY_TEMPERATURE_MAX,
};
use guardian::contract::{FaultKind, GuardianState};
use guardian::service::{self, now_ms};
use up_rust::local_transport::LocalTransport;
use up_rust::{
    LocalUriProvider, StaticUriProvider, UListener, UMessage, UMessageBuilder, UPayloadFormat,
    UTransport, UUri,
};

/// Listener that records every uMessage the Guardian publishes.
#[derive(Default)]
struct Collector(Mutex<Vec<UMessage>>);

#[async_trait]
impl UListener for Collector {
    async fn on_receive(&self, msg: UMessage) {
        self.0.lock().unwrap().push(msg);
    }
}

impl Collector {
    /// Decodes the payloads of all recorded messages from one topic
    /// (heartbeat, state, ...) into the matching contract struct.
    fn payloads<T: serde::de::DeserializeOwned>(&self, resource_id: u16) -> Vec<T> {
        self.0
            .lock()
            .unwrap()
            .iter()
            .filter(|m| m.source().map(|s| s.resource_id()) == Some(resource_id))
            .map(|m| {
                assert_eq!(
                    m.payload_format(),
                    Some(UPayloadFormat::UPAYLOAD_FORMAT_JSON)
                );
                serde_json::from_slice(m.payload.as_ref().unwrap()).unwrap()
            })
            .collect()
    }
}

/// Publishes a raw payload, like the VSS publisher would.
async fn publish(transport: &LocalTransport, topic: &UUri, payload: Vec<u8>) {
    let msg = UMessageBuilder::publish(topic.clone())
        .build_with_payload(payload, UPayloadFormat::UPAYLOAD_FORMAT_JSON)
        .unwrap();
    transport.send(msg).await.unwrap();
}

// 4 valid samples and one broken payload. Expected: one CLEAR -> MONITORING
// event (triggered by sample 3), one PayloadInvalid fault, and heartbeats
// showing MONITORING with 4 accepted samples.
#[tokio::test(flavor = "multi_thread")]
async fn guardian_consumes_vss_and_publishes_events_over_uprotocol() {
    let transport = Arc::new(LocalTransport::default());
    // Faster timers so the test needs only a few hundred milliseconds.
    let mut cfg = GuardianConfig::default();
    cfg.uprotocol.heartbeat_period_ms = 50;
    cfg.uprotocol.tick_period_ms = 10;

    // Listen to all Guardian topics (resource FFFF = wildcard).
    let collector = Arc::new(Collector::default());
    transport
        .register_listener(
            &UUri::from_str("//*/8002/1/FFFF").unwrap(),
            None,
            collector.clone(),
        )
        .await
        .unwrap();

    // Run the service in the background; sending on stop_tx stops it.
    let (stop_tx, stop_rx) = tokio::sync::oneshot::channel::<()>();
    let service = tokio::spawn(service::run(transport.clone(), cfg, async {
        let _ = stop_rx.await;
    }));
    // Give the service time to register its input listener.
    tokio::time::sleep(Duration::from_millis(100)).await;

    // Publish as the VSS publisher: //vehicle/8001/1/8001.
    let start_ms = now_ms();
    let topic = StaticUriProvider::new("vehicle", 0x8001, 1).get_resource_uri(0x8001);
    for counter in 1..=4 {
        let sample = VssSample {
            path: VSS_BATTERY_TEMPERATURE_MAX.into(),
            value: 30.0 + counter as f64 * 0.1,
            rolling_counter: counter,
            correlation_id: Some("it-1".into()),
        };
        publish(&transport, &topic, serde_json::to_vec(&sample).unwrap()).await;
        tokio::time::sleep(Duration::from_millis(20)).await;
    }
    let end_ms = now_ms();
    publish(&transport, &topic, b"not a vss sample".to_vec()).await;
    // Let a few more heartbeats go out, then stop.
    tokio::time::sleep(Duration::from_millis(200)).await;

    stop_tx.send(()).unwrap();
    service.await.unwrap().unwrap();

    // State topic: exactly one transition, caused by the 3rd sample.
    let states: Vec<StateEvent> = collector.payloads(resource::STATE);
    assert_eq!(states.len(), 1, "{states:?}");
    assert_eq!(
        (states[0].from, states[0].to),
        (GuardianState::Clear, GuardianState::Monitoring)
    );
    let trigger = states[0].trigger.as_ref().unwrap();
    assert_eq!(trigger.rolling_counter, 3);
    assert!(
        trigger.message_id.is_some(),
        "uProtocol message id must be propagated"
    );
    assert_eq!(trigger.correlation_id.as_deref(), Some("it-1"));
    // The sample time comes from the uMessage id, so it must lie within the
    // time the test was publishing.
    assert!(
        (start_ms..=end_ms).contains(&trigger.sent_ms),
        "{} not in {start_ms}..={end_ms}",
        trigger.sent_ms
    );

    // Fault topic: only the broken payload.
    let faults: Vec<FaultEvent> = collector.payloads(resource::FAULT);
    assert_eq!(faults.len(), 1, "{faults:?}");
    assert_eq!(faults[0].fault, FaultKind::PayloadInvalid);

    // Heartbeat topic: periodic, numbered, with the final status.
    let heartbeats: Vec<Heartbeat> = collector.payloads(resource::HEARTBEAT);
    assert!(heartbeats.len() >= 3, "{} heartbeats", heartbeats.len());
    let last = heartbeats.last().unwrap();
    assert_eq!(last.state, GuardianState::Monitoring);
    assert_eq!(last.counters.accepted, 4);
    assert_eq!(last.rolling_counter, Some(4));
    assert!(heartbeats.windows(2).all(|w| w[0].seq < w[1].seq));
}
