/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! MQTT payload -> VssSample mapping (mapping.rs), no broker or transport.
//!
//! Each test feeds raw MQTT payload bytes (`br#"..."#` is a byte string
//! literal, so the JSON needs no escaping) and checks the resulting sample.

use vss_publisher::config::MappingConfig;
use vss_publisher::mapping::{Mapper, MappingError};

const VSS_PATH: &str = "Vehicle.Powertrain.TractionBattery.Temperature.Max";

/// A real message from the AZ3166 firmware.
const BOARD_MESSAGE: &[u8] = br#"{"pressure_hPa":1215.87,"temperature_degC":24.65,"humidity_perc":54.11,"acceleration_mg":[-38.43,13.85,1011.26],"magnetic_mG":[-91.50,-99.00,-384.00],"counter":31}"#;

fn mapper() -> Mapper {
    Mapper::new(MappingConfig::default(), None)
}

/// Minimal board-style message with only the two keys we use.
fn msg(counter: &str, temperature: &str) -> Vec<u8> {
    format!(r#"{{"temperature_degC": {temperature}, "counter": {counter}}}"#).into_bytes()
}

// The real board message: temperature and counter mapped, the other sensor
// values ignored.
#[test]
fn maps_real_board_message() {
    let s = mapper().map(BOARD_MESSAGE).unwrap();
    assert_eq!(s.path, VSS_PATH);
    assert_eq!(s.value, 24.65);
    assert_eq!(s.rolling_counter, 31);
}

// Key names come from the config, so a firmware rename needs no code change.
#[test]
fn key_names_are_configurable() {
    let cfg = MappingConfig {
        temperature_field: "temp".into(),
        counter_field: "alive".into(),
        ..MappingConfig::default()
    };
    let s = Mapper::new(cfg, None)
        .map(br#"{"temp": 30.5, "alive": 7}"#)
        .unwrap();
    assert_eq!((s.value, s.rolling_counter), (30.5, 7));
}

// Numbers sent as strings (common in embedded JSON) are accepted.
#[test]
fn numeric_strings_are_accepted() {
    let s = mapper().map(&msg("\"12\"", "\"38.25\"")).unwrap();
    assert_eq!(s.value, 38.25);
    assert_eq!(s.rolling_counter, 12);
}

// Every way a payload can be unusable gives a specific error naming the key.
#[test]
fn missing_or_invalid_fields_are_errors() {
    let m = mapper();
    assert_eq!(
        m.map(br#"{"counter": 1}"#),
        Err(MappingError::MissingField("temperature_degC".into()))
    );
    assert_eq!(
        m.map(br#"{"temperature_degC": 41.5}"#),
        Err(MappingError::MissingField("counter".into()))
    );
    // The old key names are not accepted any more.
    assert_eq!(
        m.map(br#"{"rollingCounter": 1, "temperature": 41.5}"#),
        Err(MappingError::MissingField("temperature_degC".into()))
    );
    assert!(matches!(
        m.map(&msg("1", "\"hot\"")),
        Err(MappingError::NotANumber(k, _)) if k == "temperature_degC"
    ));
    assert!(matches!(
        m.map(&msg("1", "\"NaN\"")),
        Err(MappingError::NotANumber(..))
    ));
    // Counter must be a non-negative integer.
    for counter in ["-1", "1.5", "\"x\""] {
        assert!(
            matches!(
                m.map(&msg(counter, "41.5")),
                Err(MappingError::NotACounter(k, _)) if k == "counter"
            ),
            "{counter}"
        );
    }
    // JSON null counts as "missing".
    assert_eq!(
        m.map(&msg("null", "41.5")),
        Err(MappingError::MissingField("counter".into()))
    );
    // Valid JSON, but not an object.
    assert!(matches!(m.map(b"41.5"), Err(MappingError::InvalidJson(_))));
}

// 500 C is nonsense, but filtering it here would hide it from the Guardian.
#[test]
fn implausible_temperature_is_forwarded_for_the_guardian_to_judge() {
    let s = mapper().map(&msg("1", "500")).unwrap();
    assert_eq!(s.value, 500.0);
}

// The counter is passed through as is, also repeats and the wrap-around:
// judging them (duplicate, reordering, gaps) is the Guardian's job.
#[test]
fn counter_is_passed_through_unchanged() {
    let m = mapper();
    let counters: Vec<u64> = ["254", "254", "255", "0", "3"]
        .iter()
        .map(|c| m.map(&msg(c, "41.5")).unwrap().rolling_counter)
        .collect();
    assert_eq!(counters, vec![254, 254, 255, 0, 3]);
}

// Pins the exact JSON the Guardian expects (its VssSample in contract.rs).
// If this test has to change, the Guardian has to change too.
#[test]
fn output_matches_guardian_input_contract() {
    let m = Mapper::new(MappingConfig::default(), Some("run-7".into()));
    let s = m.map(BOARD_MESSAGE).unwrap();
    let json: serde_json::Value = serde_json::to_value(&s).unwrap();
    assert_eq!(
        json,
        serde_json::json!({
            "path": VSS_PATH,
            "value": 24.65,
            "rolling_counter": 31,
            "correlation_id": "run-7",
        })
    );
}
