/********************************************************************************
 * Copyright (c) 2026 FEVengers contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed the code and verified it with the included tests.
 *
 * SPDX-License-Identifier: EPL-2.0 AND CC0-1.0
 ********************************************************************************/

//! Published uMessages, checked on up-rust's in-process LocalTransport.
//!
//! Mapper + publisher together, without MQTT and without Zenoh: a listener
//! registered with the Guardian's input filter must receive exactly the
//! uMessage the Guardian would get.

use std::str::FromStr;
use std::sync::{Arc, Mutex};

use async_trait::async_trait;
use up_rust::local_transport::LocalTransport;
use up_rust::{UListener, UMessage, UMessageType, UPayloadFormat, UTransport, UUri};
use vss_publisher::config::{MappingConfig, UProtocolConfig};
use vss_publisher::mapping::{Mapper, VssSample};
use vss_publisher::publisher::VssPublisher;

/// Listener that records every received uMessage (stands in for the Guardian).
#[derive(Default)]
struct Collector(Mutex<Vec<UMessage>>);

#[async_trait]
impl UListener for Collector {
    async fn on_receive(&self, msg: UMessage) {
        self.0.lock().unwrap().push(msg);
    }
}

// One MQTT payload in -> one PUBLISH uMessage out, on //vehicle/8001/1/8001,
// JSON format, with a message ID and the mapped sample as payload.
#[tokio::test]
async fn reading_is_published_as_json_umessage_on_guardian_input_topic() {
    let transport = Arc::new(LocalTransport::default());
    let collector = Arc::new(Collector::default());
    // The Guardian's default input filter.
    let guardian_filter = UUri::from_str("//*/8001/1/8001").unwrap();
    transport
        .register_listener(&guardian_filter, None, collector.clone())
        .await
        .unwrap();

    // Same steps as main.rs does for every MQTT message: map, then publish.
    let publisher = VssPublisher::new(transport.clone(), &UProtocolConfig::default());
    let mapper = Mapper::new(MappingConfig::default(), None);
    let sample = mapper
        .map(br#"{"temperature_degC": 41.5, "counter": 1}"#)
        .unwrap();
    publisher.publish(&sample).await.unwrap();

    // LocalTransport delivers synchronously, so the message is already here.
    let msgs = collector.0.lock().unwrap();
    assert_eq!(msgs.len(), 1);
    let msg = &msgs[0];
    assert_eq!(msg.type_(), Some(UMessageType::UMESSAGE_TYPE_PUBLISH));
    assert_eq!(
        msg.payload_format(),
        Some(UPayloadFormat::UPAYLOAD_FORMAT_JSON)
    );
    assert_eq!(msg.source().unwrap().to_uri(false), "//vehicle/8001/1/8001");
    // The id is a UUIDv7 carrying the creation time: the sample time.
    assert!(msg.id().and_then(|id| id.get_time()).is_some());
    // Payload decodes back to exactly the sample we published.
    let received: VssSample = serde_json::from_slice(msg.payload.as_ref().unwrap()).unwrap();
    assert_eq!(received, sample);
}
